import { db } from '@/db';
import { flashcards } from '@/db/schema';

async function main() {
    const sampleFlashcards = [
        // Price Elasticity of Supply - PES (5 flashcards)
        {
            question: 'What is the formula for Price Elasticity of Supply (PES) and what does it measure?',
            answer: 'PES = (% change in Quantity Supplied) / (% change in Price). It measures the responsiveness of quantity supplied to a change in price. PES is always positive because price and quantity supplied move in the same direction according to the law of supply.',
            level: 'JC',
            category: 'Economics',
            topic: 'Price Elasticity of Supply (PES)',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the different types of Price Elasticity of Supply and their PES values.',
            answer: 'Elastic supply (PES > 1): Quantity supplied changes by a larger percentage than price. Inelastic supply (PES < 1): Quantity supplied changes by a smaller percentage than price. Unit elastic (PES = 1): Percentage change in quantity supplied equals percentage change in price. Perfectly elastic (PES = ∞): Any price change causes infinite supply response. Perfectly inelastic (PES = 0): Quantity supplied does not respond to price changes.',
            level: 'JC',
            category: 'Economics',
            topic: 'Price Elasticity of Supply (PES)',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What are the four main determinants of Price Elasticity of Supply (MEAT)?',
            answer: 'M - Mobility of factors of production: Easy reallocation of resources makes supply more elastic. E - Excess capacity: Spare capacity allows quick supply response, making supply elastic. A - Availability of stocks: Storable goods can adjust supply quickly from inventory, increasing elasticity. T - Time period: Short run supply is relatively inelastic due to fixed factors; long run supply is more elastic as firms adjust all inputs.',
            level: 'JC',
            category: 'Economics',
            topic: 'Price Elasticity of Supply (PES)',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain how Mobility of factors and Excess capacity affect Price Elasticity of Supply.',
            answer: 'Mobility of factors: When resources can be easily reallocated between different uses, supply is more elastic. For example, unskilled labor is mobile and can switch jobs easily, making supply elastic. Specialized machinery is immobile, making supply inelastic. Excess capacity: When firms have spare capacity (unused machinery, idle workers), they can quickly increase production when prices rise, making supply elastic. At full capacity, supply becomes inelastic as firms cannot easily expand output.',
            level: 'JC',
            category: 'Economics',
            topic: 'Price Elasticity of Supply (PES)',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'How does time period affect Price Elasticity of Supply? Compare short run and long run PES.',
            answer: 'Short run PES: Relatively inelastic because firms have at least one fixed factor (e.g., factory size, capital equipment). They can only vary variable inputs like labor and raw materials, limiting supply response. Long run PES: More elastic because all factors are variable. Firms can build new factories, purchase more equipment, and new firms can enter the market. Existing firms can also exit. This allows much greater adjustment to price changes, making long run supply more responsive.',
            level: 'JC',
            category: 'Economics',
            topic: 'Price Elasticity of Supply (PES)',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Income Elasticity of Demand - YED (3 flashcards)
        {
            question: 'What is Income Elasticity of Demand (YED) and how do you classify goods based on YED values?',
            answer: 'YED = (% change in Quantity Demanded) / (% change in Income). Normal goods (YED > 0): demand rises with income. These include necessities (0 < YED < 1) like bread, basic clothing, public transport with YED = 0.2-0.8, and luxuries (YED > 1) like sports cars, fine dining, overseas travel, designer goods with YED > 1.5. Inferior goods (YED < 0): demand falls as income rises, such as instant noodles, second-hand goods, and bus travel when cars become affordable.',
            level: 'JC',
            category: 'Economics',
            topic: 'Income Elasticity of Demand (YED)',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Distinguish between necessities and luxuries using Income Elasticity of Demand. Provide specific examples.',
            answer: 'Necessities (0 < YED < 1): Income inelastic normal goods where demand rises less than proportionately with income. Examples: bread (YED ≈ 0.2), basic clothing (YED ≈ 0.5), public transport (YED ≈ 0.6-0.8). People need these goods regardless of income level. Luxuries (YED > 1): Income elastic normal goods where demand rises more than proportionately with income. Examples: sports cars (YED ≈ 2.5), fine dining (YED ≈ 1.8), overseas travel (YED ≈ 2.0), designer goods (YED > 1.5). These are wants that people consume more of as they become wealthier.',
            level: 'JC',
            category: 'Economics',
            topic: 'Income Elasticity of Demand (YED)',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'How can businesses use Income Elasticity of Demand for planning? Explain applications during economic growth and recession.',
            answer: 'During economic growth (rising incomes): Businesses selling luxuries (YED > 1) will see demand rise significantly and should expand capacity. Necessity producers see modest demand increases. Inferior good producers face falling demand and should diversify. During recession (falling incomes): Luxury good businesses face sharp demand declines and should cut costs or shift to necessities. Necessity demand remains relatively stable. Inferior good demand may actually increase, presenting opportunities. Businesses use YED to forecast demand changes, plan production capacity, set pricing strategies, and make investment decisions based on expected income trends in the economy.',
            level: 'JC',
            category: 'Economics',
            topic: 'Income Elasticity of Demand (YED)',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Cross Elasticity of Demand - XED (2 flashcards)
        {
            question: 'What is Cross Elasticity of Demand (XED)? Explain substitutes and complements with examples.',
            answer: 'XED = (% change in Quantity Demanded of good A) / (% change in Price of good B). Substitutes (XED > 0): When price of good B rises, demand for good A increases. Strong substitutes have high XED (> 1) like Coke/Pepsi, butter/margarine. Weak substitutes have 0 < XED < 1. Complements (XED < 0): When price of good B rises, demand for good A falls. Strong complements have large negative XED (< -1) like cars/petrol, printers/ink cartridges. Weak complements have -1 < XED < 0. Unrelated goods (XED ≈ 0): No relationship, like shoes and coffee.',
            level: 'JC',
            category: 'Economics',
            topic: 'Cross Elasticity of Demand (XED)',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'How do businesses use Cross Elasticity of Demand in pricing and marketing strategies?',
            answer: 'For substitutes (positive XED): Firms monitor competitor prices closely. If a rival raises prices, a firm can maintain prices to capture market share as consumers switch. They may also differentiate products to reduce XED and substitutability. For complements (negative XED): Firms may sell complementary goods together or price one low to boost demand for the other. For example, printers sold cheaply to increase demand for profitable ink cartridges, or gaming consoles sold at low margins to drive game sales. High XED indicates intense competition and price sensitivity. Low XED suggests brand loyalty or product differentiation, allowing more pricing power.',
            level: 'JC',
            category: 'Economics',
            topic: 'Cross Elasticity of Demand (XED)',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Price Ceiling (2 flashcards)
        {
            question: 'What is a price ceiling? Explain its effects on the market including shortage, winners, and losers.',
            answer: 'Price ceiling: Maximum legal price set below free market equilibrium by government. Effects: Creates shortage (Qd > Qs at ceiling price) because quantity demanded exceeds quantity supplied. Black markets emerge as consumers willing to pay higher prices seek sellers. Non-price rationing occurs through queues, favoritism, or discrimination. Winners: Consumers who successfully obtain goods at the lower price. Losers: Consumers unable to find goods due to shortage, and producers who receive lower prices and reduced revenue. Examples: rent controls create affordable housing but cause housing shortages; food price controls in wartime.',
            level: 'JC',
            category: 'Economics',
            topic: 'Price Ceiling',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Analyze the welfare effects of price ceilings using consumer surplus, producer surplus, and deadweight loss.',
            answer: 'Consumer surplus: Ambiguous change. Some consumers gain surplus by paying lower prices, but others lose access entirely due to shortage. Net effect depends on who gets the limited supply. Producer surplus: Decreases unambiguously. Producers receive lower prices and sell less quantity, losing revenue and surplus on both margins. Deadweight loss: Created by the quantity reduction from equilibrium. Mutually beneficial trades between the shortage quantity and equilibrium quantity do not occur. Total welfare falls. Additional costs include black market transactions, time wasted queuing, and resources spent on non-price competition. Despite intentions to help consumers, price ceilings often reduce overall welfare and create inefficiencies.',
            level: 'JC',
            category: 'Economics',
            topic: 'Price Ceiling',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Price Floor (2 flashcards)
        {
            question: 'What is a price floor? Explain its effects and provide examples including minimum wage.',
            answer: 'Price floor: Minimum legal price set above free market equilibrium. Effects: Creates surplus (Qs > Qd at floor price) because quantity supplied exceeds quantity demanded. Unsold inventory accumulates. Government responses include purchasing surplus (storage costs) or imposing production quotas. Examples: Agricultural price supports where government buys excess crops to maintain farmer incomes. Minimum wage creates unemployment as quantity supplied of labor exceeds quantity demanded. Workers willing to work at the higher wage cannot find jobs, representing surplus labor. Price floors aim to help producers/workers but create inefficiencies.',
            level: 'JC',
            category: 'Economics',
            topic: 'Price Floor',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Analyze the welfare effects of price floors and explain the distributional impacts of minimum wage.',
            answer: 'Consumer surplus: Decreases unambiguously. Consumers pay higher prices and consume less quantity, losing surplus on both margins. Producer surplus: May increase or decrease. Producers receive higher prices per unit (gain) but sell less quantity (loss). Net effect depends on demand elasticity. Deadweight loss: Created from quantity reduction. Mutually beneficial trades between new quantity and equilibrium do not occur, reducing total welfare. Minimum wage analysis: Winners are workers who keep jobs at higher wages, gaining income. Losers are unemployed workers priced out of the labor market who would have worked at lower wages. Young, unskilled workers are most affected by job losses.',
            level: 'JC',
            category: 'Economics',
            topic: 'Price Floor',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Indirect Taxes (4 flashcards)
        {
            question: 'Compare specific tax and ad valorem tax. How do they affect the supply curve differently?',
            answer: 'Specific tax: Fixed amount per unit (e.g., $2 per liter of petrol). Supply curve shifts vertically upward by the exact tax amount. The vertical distance between original and new supply curves remains constant at all quantities. Ad valorem tax: Percentage of price (e.g., 10% GST or VAT). Supply curve shifts by a percentage. The vertical gap between original and new supply curves widens at higher prices and quantities because the tax amount increases as price increases. Both taxes shift supply leftward/upward, reducing equilibrium quantity and raising price to consumers, but ad valorem creates a proportionally larger shift at higher price levels.',
            level: 'JC',
            category: 'Economics',
            topic: 'Indirect Taxes',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain tax incidence. When do consumers pay more of the tax burden versus producers?',
            answer: 'Tax incidence: The burden of tax shared between consumers and producers based on relative elasticities. Consumers pay more when: (1) Demand is inelastic - consumers cannot easily reduce quantity when price rises, so they absorb the tax; OR (2) Supply is elastic - producers can easily reduce supply and refuse to absorb tax costs. Producers pay more when: (1) Supply is inelastic - producers cannot easily reduce quantity supplied, forced to accept lower net price; OR (2) Demand is elastic - consumers easily reduce quantity when price rises, forcing producers to absorb tax to maintain sales. Formula: Consumer burden = (PES)/(PED+PES) × Tax. Producer burden = (PED)/(PED+PES) × Tax.',
            level: 'JC',
            category: 'Economics',
            topic: 'Indirect Taxes',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What are the effects of an indirect tax on market equilibrium? Include price, quantity, and revenue analysis.',
            answer: 'Effects of indirect tax: (1) Equilibrium quantity falls because tax increases costs, reducing supply. (2) Price to consumers rises but by less than full tax amount. (3) Price received by producers falls (price to consumers minus tax). (4) Tax revenue = tax per unit × new equilibrium quantity. Government collects this revenue. (5) The price increase to consumers and price decrease to producers sum to the total tax amount. (6) Both consumer and producer surplus decrease. (7) Total surplus falls by more than tax revenue gained, creating deadweight loss from reduced transactions. The market becomes less efficient, with welfare loss from trades that no longer occur.',
            level: 'JC',
            category: 'Economics',
            topic: 'Indirect Taxes',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Calculate tax incidence and explain deadweight loss using a cigarette tax example with specific elasticity values.',
            answer: 'Example: $10 cigarette tax with inelastic demand (PED = 0.3) and elastic supply (PES = 1.5). Consumer burden = (1.5)/(0.3+1.5) × $10 = (1.5/1.8) × $10 = $8.33. Producer burden = (0.3)/(0.3+1.5) × $10 = (0.3/1.8) × $10 = $1.67. Consumers pay most of the tax because demand is inelastic (addiction makes consumers unable to quit easily). Deadweight loss triangle: Formed between original equilibrium quantity and new lower quantity. Bounded by demand curve above and supply curve below. Represents welfare loss from smokers who would have bought cigarettes at original price but not at the higher taxed price, and producers who would have sold to them. These mutually beneficial trades no longer occur.',
            level: 'JC',
            category: 'Economics',
            topic: 'Indirect Taxes',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Subsidies (2 flashcards)
        {
            question: 'What is a subsidy and how does it affect market equilibrium? Include effects on price, quantity, and the supply curve.',
            answer: 'Subsidy: Per-unit payment from government to producers, reduces production costs. Effects: Supply curve shifts right/downward by the subsidy amount because producers can afford to supply more at each price. Equilibrium quantity increases as more is produced and consumed. Price to consumers falls, making goods more affordable. Price received by producers (market price plus subsidy) rises, incentivizing production. The subsidy creates a wedge between what consumers pay and what producers receive. Government expenditure equals subsidy per unit multiplied by new equilibrium quantity. Unlike taxes, subsidies increase market quantity and reduce prices, encouraging consumption and production of the subsidized good.',
            level: 'JC',
            category: 'Economics',
            topic: 'Subsidies',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain subsidy incidence and welfare effects. When do consumers versus producers benefit more? Provide examples.',
            answer: 'Subsidy incidence: Benefits shared based on elasticities. Consumers benefit more (larger price decrease) when: (1) Demand is elastic - consumers very responsive to price falls; OR (2) Supply is inelastic - producers cannot easily expand so pass benefits to consumers. Producers benefit more (keep more of subsidy) when: (1) Supply is elastic - can easily expand production; OR (2) Demand is inelastic - consumers not very responsive. Welfare: Consumer surplus increases (lower prices, more consumption). Producer surplus increases (higher revenues). However, government expenditure may exceed combined surplus gains, creating deadweight loss. Examples: Agricultural subsidies lower food prices (consumer benefit). Education subsidies increase access and enrollment. Renewable energy subsidies accelerate adoption and lower costs.',
            level: 'JC',
            category: 'Economics',
            topic: 'Subsidies',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Demand and Supply',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(flashcards).values(sampleFlashcards);
    
    console.log('✅ Flashcards seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});