import { db } from '@/db';
import { flashcards } from '@/db/schema';

async function main() {
    const currentTimestamp = new Date().toISOString();
    
    const sampleFlashcards = [
        // Perfect Competition (10 flashcards)
        {
            question: 'Define perfect competition and list all five key assumptions that characterize this market structure.',
            answer: 'Perfect competition is a market structure where no single buyer or seller has market power. The five key assumptions are: (1) Many buyers and sellers - each firm is a price taker with negligible market share, (2) Homogeneous products - goods are perfect substitutes with no differentiation, (3) Perfect information - all market participants have complete knowledge of prices, quality, and market conditions, (4) Free entry and exit - no barriers prevent firms from entering or leaving the market in the long run, (5) Perfect factor mobility - resources can move freely between uses without cost or delay.',
            level: 'JC',
            category: 'Economics',
            topic: 'Perfect Competition - Definition and Assumptions',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain the short-run equilibrium for a perfectly competitive firm making supernormal profit. Include the profit maximization condition and illustrate with a diagram description.',
            answer: 'In the short run, a perfectly competitive firm maximizes profit where MC = MR = AR = P. When market price is above average cost (P > AC), the firm earns supernormal profit. The firm produces at quantity Q* where MC intersects MR. The profit per unit is (P - AC), and total supernormal profit is the area of the rectangle with height (P - AC) and width Q*. The firm is a price taker, so its AR and MR curves are horizontal at the market price. The firm will continue producing as long as P ≥ AVC to cover variable costs.',
            level: 'JC',
            category: 'Economics',
            topic: 'Perfect Competition - Short-run Supernormal Profit',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Describe the short-run scenarios where a perfectly competitive firm makes normal profit or losses. When should the firm shut down?',
            answer: 'Normal profit occurs when P = AC at the profit-maximizing output where MC = MR. The firm covers all explicit and implicit costs but earns zero economic profit. Losses occur when P < AC. The firm should continue operating if P ≥ AVC (covering variable costs and contributing to fixed costs). The shutdown point is where P = AVC at minimum AVC. Below this price, the firm minimizes losses by shutting down as it cannot cover variable costs. The firm will make losses equal to total fixed costs if it shuts down, but greater losses if it continues production when P < AVC.',
            level: 'JC',
            category: 'Economics',
            topic: 'Perfect Competition - Short-run Normal Profit and Losses',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain the long-run equilibrium in perfect competition and the entry/exit mechanism that leads to zero economic profit.',
            answer: 'In long-run equilibrium, perfectly competitive firms earn zero economic profit (normal profit only) where P = MC = AC at minimum AC. The entry/exit mechanism works as follows: If firms make supernormal profits, this attracts new entrants (due to free entry assumption). Increased supply shifts the market supply curve right, lowering market price until P = AC. If firms make losses, some exit the market, shifting supply left and raising price until P = AC. This process continues until all firms earn only normal profit. At this point, there is no incentive for entry or exit, establishing long-run equilibrium. Firms produce at the productively efficient output level.',
            level: 'JC',
            category: 'Economics',
            topic: 'Perfect Competition - Long-run Equilibrium',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'What is allocative efficiency? Explain how perfect competition achieves allocative efficiency and why this maximizes total economic welfare.',
            answer: 'Allocative efficiency occurs when resources are allocated to produce the combination of goods that society values most, achieved when P = MC. In perfect competition, firms produce where P = MC because they maximize profit where MC = MR, and P = MR for price takers. At this point, the marginal benefit to consumers (reflected in price/willingness to pay) equals the marginal cost to society of producing the last unit. This eliminates deadweight loss and maximizes total surplus (consumer surplus + producer surplus). No reallocation of resources could make someone better off without making someone else worse off (Pareto efficiency). Society produces the socially optimal quantity where marginal social benefit equals marginal social cost.',
            level: 'JC',
            category: 'Economics',
            topic: 'Perfect Competition - Allocative Efficiency',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Define productive efficiency and explain how perfect competition achieves it in the long run.',
            answer: 'Productive efficiency occurs when firms produce at minimum average cost (AC), using the least costly combination of inputs to produce a given output level. In perfect competition, long-run equilibrium forces firms to produce at minimum AC. This happens because: (1) Competition drives economic profits to zero, so P = AC, (2) Profit maximization requires MC = P, (3) Therefore MC = AC, which only occurs at minimum AC. Firms operating above minimum AC would make losses and exit. Firms that innovate to reduce costs below minimum AC gain temporary competitive advantage but competition eventually eliminates this. Productive efficiency means no waste in production and technical efficiency is achieved.',
            level: 'JC',
            category: 'Economics',
            topic: 'Perfect Competition - Productive Efficiency',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain how perfect competition maximizes consumer surplus and producer surplus. Use the concepts of demand and supply curves in your answer.',
            answer: 'Perfect competition maximizes total surplus by producing at the market equilibrium where supply (sum of MC curves) equals demand (marginal benefit). Consumer surplus is the area below the demand curve and above the price, representing the difference between what consumers are willing to pay and what they actually pay. Producer surplus is the area above the supply curve and below the price, representing the difference between the price received and the minimum price firms would accept. At equilibrium quantity where S = D, total surplus (CS + PS) is maximized. Any quantity less than equilibrium creates deadweight loss as there are mutually beneficial trades not occurring. Any quantity greater creates deadweight loss as marginal cost exceeds marginal benefit. Perfect competition achieves this maximum without any deadweight loss.',
            level: 'JC',
            category: 'Economics',
            topic: 'Perfect Competition - Consumer and Producer Surplus',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Why is perfect competition considered the benchmark model for evaluating other market structures? What are its welfare implications?',
            answer: 'Perfect competition serves as the benchmark because it achieves both allocative and productive efficiency, maximizing social welfare. It represents the ideal outcome where: (1) Resources are allocated optimally (P = MC), (2) Production occurs at lowest cost (minimum AC), (3) Total surplus is maximized with no deadweight loss, (4) Consumer sovereignty prevails as production responds to consumer preferences, (5) No firm has market power to exploit consumers. All other market structures are evaluated against this benchmark. Deviations from perfect competition typically result in lower output, higher prices, and welfare losses. However, this benchmark has limitations in real-world applications where its assumptions rarely hold completely. Despite these limitations, it provides a useful theoretical standard for identifying market failures and inefficiencies.',
            level: 'JC',
            category: 'Economics',
            topic: 'Perfect Competition - Benchmark Model',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Critically evaluate the limitations and unrealistic assumptions of the perfect competition model. How do these affect its applicability to real-world markets?',
            answer: 'The perfect competition model has several unrealistic assumptions that limit its real-world applicability: (1) Homogeneous products - most real markets have differentiated products, branding, and quality variations, (2) Perfect information - consumers and firms rarely have complete information about prices, quality, and market conditions; search costs exist, (3) Many small firms - many industries have significant economies of scale making small size inefficient, (4) Free entry/exit - most markets have barriers such as capital requirements, regulations, patents, (5) Perfect factor mobility - resources cannot instantly move between uses; there are adjustment costs and immobile factors. Additionally, the model ignores: transaction costs, innovation and dynamic efficiency, product variety preferences, and the time needed to reach equilibrium. Despite these limitations, the model remains valuable as a theoretical benchmark and approximates some agricultural and commodity markets reasonably well.',
            level: 'JC',
            category: 'Economics',
            topic: 'Perfect Competition - Limitations and Assumptions',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'How does the perfectly competitive firm\'s demand curve differ from the market demand curve? Explain the relationship between AR, MR, and price for a price-taking firm.',
            answer: 'The market demand curve is downward sloping, showing the inverse relationship between price and quantity demanded for the entire market. However, an individual perfectly competitive firm faces a perfectly elastic (horizontal) demand curve at the market price because the firm is a price taker - it can sell any quantity at the market price but nothing above it. For a price-taking firm: AR (Average Revenue) = P = MR (Marginal Revenue). This occurs because selling an additional unit adds exactly the market price to total revenue, with no need to lower price on previous units. The firm\'s demand curve is also its AR and MR curve. While the firm can choose its quantity, it has no control over price. This contrasts sharply with imperfectly competitive firms where MR < P due to downward sloping demand curves requiring price reductions to sell more units.',
            level: 'JC',
            category: 'Economics',
            topic: 'Perfect Competition - Demand Curves and Revenue',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        
        // Monopoly (10 flashcards)
        {
            question: 'Define monopoly and explain its key characteristics. How does being a price maker differ from being a price taker?',
            answer: 'A monopoly is a market structure with a single seller of a product with no close substitutes, giving the firm significant market power. Key characteristics include: (1) Single seller - one firm supplies the entire market, (2) Unique product - no close substitutes available, (3) Price maker - the firm can influence market price by adjusting output, (4) High barriers to entry - prevents competition from entering, (5) Significant market power - can earn supernormal profits in long run. As a price maker, the monopolist faces the downward-sloping market demand curve and must choose a price-quantity combination on this curve. Unlike a price taker in perfect competition who accepts the market price, the monopolist must trade off higher prices against lower quantities sold. The monopolist cannot set both price and quantity independently - setting a higher price reduces quantity demanded.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopoly - Definition and Characteristics',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain the three types of barriers to entry that protect monopoly power: structural, strategic, and statutory barriers. Provide specific examples of each.',
            answer: 'Barriers to entry protect monopolies from competition: (1) Structural barriers arise from market conditions: Economies of scale - large firms have cost advantages (natural monopolies like utilities), High capital requirements - massive investment needed (aircraft manufacturing), Control of essential resources - owning key inputs (De Beers diamond mines), Network effects - value increases with users (social media platforms). (2) Strategic barriers result from incumbent firm actions: Predatory pricing - temporarily pricing below cost to drive out competitors, Limit pricing - setting prices low enough to deter entry while remaining profitable, Exclusive contracts - tying up suppliers or distributors, Brand loyalty and advertising - creating switching costs. (3) Statutory barriers created by government: Patents and copyrights - legal monopolies for intellectual property (pharmaceutical drugs), Licenses and franchises - government grants exclusive rights (utilities, taxis), Legal barriers - regulations restricting entry (professional services requiring certification).',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopoly - Barriers to Entry Types',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain monopoly profit maximization. Why does the monopolist produce where MC = MR but P > MR? Describe markup pricing.',
            answer: 'A monopolist maximizes profit by producing where MC = MR, but unlike perfect competition, P > MR due to the downward-sloping demand curve. To sell additional units, the monopolist must lower price on all units (assuming no price discrimination), so MR < P. The MR curve lies below the demand (AR) curve and falls twice as fast. The monopolist produces quantity Q* where MC = MR, then charges the maximum price P* consumers will pay for that quantity (reading off the demand curve). The difference (P* - MC) represents the markup over marginal cost. Markup pricing formula: Markup = (P - MC)/P = 1/|PED|, where PED is price elasticity of demand. The less elastic demand, the higher the markup. Supernormal profit equals (P - AC) × Q. Unlike perfect competition, barriers to entry allow these profits to persist in the long run.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopoly - Profit Maximization and Markup Pricing',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'What is a natural monopoly? Explain how economies of scale throughout the relevant market demand range lead to natural monopoly, and describe the LRAC curve characteristics.',
            answer: 'A natural monopoly exists when economies of scale are so significant that one firm can supply the entire market at lower cost than multiple firms could. The long-run average cost (LRAC) curve continues declining throughout the relevant range of market demand, meaning average cost falls as output increases across the entire market quantity. Characteristics: (1) High fixed costs and low marginal costs (utilities, railways, water supply), (2) LRAC declines over the entire market demand range, (3) Minimum efficient scale exceeds market demand, (4) Duplication of infrastructure is wasteful and inefficient. If multiple firms operated, each would produce at higher AC due to smaller scale, increasing costs to consumers. Examples include electricity distribution, water supply, and railway networks where massive infrastructure investment is required. Natural monopolies present a policy dilemma - monopoly is most efficient structure but requires regulation to prevent exploitation of market power through excessive prices.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopoly - Natural Monopoly',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain allocative inefficiency in monopoly. How does producing where P > MC create deadweight loss? Illustrate with the deadweight loss triangle.',
            answer: 'Monopoly creates allocative inefficiency because it produces where P > MC, unlike perfect competition where P = MC. The monopolist restricts output to Qm (where MC = MR) and charges Pm, compared to competitive output Qc where P = MC. Deadweight loss is the welfare loss triangle between Qm and Qc, bounded by the demand curve above and MC curve below. This represents: (1) Lost consumer surplus - consumers willing to pay more than MC but less than Pm are excluded from the market, (2) Foregone mutually beneficial trades - units between Qm and Qc have marginal benefit (on demand curve) exceeding marginal cost, but aren\'t produced. The monopolist doesn\'t produce these units because MR < MC for them, even though P > MC. Society loses the total surplus that these units would have generated. The size of deadweight loss depends on demand elasticity and the difference between Pm and Pc - greater market power and less elastic demand create larger welfare losses.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopoly - Allocative Inefficiency and Deadweight Loss',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Why is monopoly productively inefficient? Explain the concept of X-inefficiency and why monopolies may not produce at minimum average cost.',
            answer: 'Monopolies are productively inefficient because they typically do not produce at minimum AC. Unlike perfect competition where competition forces firms to minimize costs, monopolies lack competitive pressure. Reasons include: (1) Profit maximization focus - monopolist produces where MC = MR, which may not coincide with minimum AC, (2) No competitive pressure - barriers to entry mean inefficient firms can survive, (3) X-inefficiency - organizational slack and waste when firms don\'t face competitive discipline. X-inefficiency refers to costs being higher than technically necessary due to: lack of managerial incentives to minimize costs, bureaucratic inefficiency, wasteful spending (lavish offices, excessive perks), slow adoption of cost-reducing innovations, comfortable life for managers without competitive threats. The monopolist may produce at various points on the AC curve depending on demand and cost conditions, often above minimum AC. Even if economies of scale are exhausted, monopoly output may be in the increasing or constant returns region of the LRAC curve.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopoly - Productive Inefficiency and X-inefficiency',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Compare consumer surplus and producer surplus in monopoly versus perfect competition. Explain the redistribution effect and the deadweight loss effect.',
            answer: 'Monopoly causes significant changes in surplus distribution compared to perfect competition: Consumer Surplus (CS): Decreases substantially - consumers pay higher price (Pm > Pc) and consume less (Qm < Qc). Part of CS is transferred to producer as higher prices, part becomes deadweight loss. Producer Surplus (PS): May increase or decrease overall - the monopolist gains surplus from higher prices (redistribution from consumers) but loses potential surplus from foregone trades (deadweight loss). Net effect depends on demand elasticity and cost structure. The redistribution effect: Area of CS transferred to PS as monopolist charges higher prices - wealth transfer from consumers to monopoly, not necessarily an efficiency loss but an equity concern. The deadweight loss effect: Total surplus (CS + PS) is smaller in monopoly - represents pure welfare loss to society with no offsetting gain, units not produced despite marginal benefit exceeding marginal cost. While monopolist may benefit from market power, society as a whole loses welfare due to restricted output and higher prices.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopoly - Consumer and Producer Surplus Comparison',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain the three degrees of price discrimination: first degree (perfect), second degree (quantity discounts), and third degree (market segmentation). What conditions are necessary for price discrimination to work?',
            answer: 'Price discrimination involves charging different prices to different consumers for the same product: First degree (perfect) price discrimination: Charging each consumer their maximum willingness to pay, extracting all consumer surplus. Theoretical concept rarely achieved in practice. Example: Personalized negotiated prices. Second degree (quantity discounts): Prices vary based on quantity purchased or product version, consumers self-select. Examples: Bulk discounts, airline seat classes, software versions (basic/premium). Third degree (market segmentation): Different prices to identifiable consumer groups with different demand elasticities. Examples: Student discounts, senior citizen rates, geographic pricing, peak/off-peak pricing. Necessary conditions for successful price discrimination: (1) Market power - firm must be price maker to set different prices, (2) Prevent resale/arbitrage - consumers buying at low price cannot resell to high-price consumers (services are ideal), (3) Different price elasticities of demand - groups must have different willingness to pay and responsiveness to price, (4) Ability to identify and separate markets - firm must distinguish between consumer groups.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopoly - Price Discrimination Types and Conditions',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Evaluate the advantages of monopoly, particularly regarding economies of scale and dynamic efficiency through R&D investment.',
            answer: 'Despite inefficiencies, monopolies have potential advantages: Economies of scale: (1) Natural monopolies can produce at lower AC than multiple competitors due to declining LRAC throughout market range, (2) Large-scale production reduces unit costs, benefiting consumers through lower prices than multiple small firms, (3) Avoids wasteful duplication of fixed costs and infrastructure. Dynamic efficiency and innovation: (1) Supernormal profits provide funds for research and development - monopolies can afford substantial R&D investment, (2) Incentive to innovate - prospect of monopoly profits from successful innovation drives R&D, (3) Patents and intellectual property protection encourage innovation by guaranteeing temporary monopoly returns, (4) Long-term perspective - absence of competitive pressure allows focus on long-term innovation rather than short-term survival. Examples: Pharmaceutical companies invest billions in drug development due to patent protection; Technology firms like Google innovate extensively funded by market dominance. However, these advantages must be weighed against allocative and productive inefficiencies. The Schumpeterian view suggests monopoly profits are necessary for innovation in capitalism.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopoly - Advantages: Economies of Scale and Dynamic Efficiency',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Evaluate the disadvantages of monopoly for consumers and society, including higher prices, lower output, deadweight loss, and X-inefficiency.',
            answer: 'Monopoly creates several significant disadvantages: Higher prices and lower output: (1) Price exceeds marginal cost (P > MC), creating allocative inefficiency, (2) Consumers pay more and consume less than under perfect competition, (3) Reduces consumer surplus significantly, transferring it to producer, (4) Restricts access to goods, particularly hurting low-income consumers. Deadweight loss: (1) Foregone mutually beneficial trades between Qm and Qc, (2) Society loses total surplus that would have been generated, (3) Pure welfare loss with no offsetting gain to anyone, (4) Magnitude depends on demand elasticity and degree of market power. X-inefficiency and waste: (1) Lack of competitive pressure reduces incentive to minimize costs, (2) Organizational slack and managerial complacency, (3) Costs higher than technically necessary, (4) Slow adoption of cost-reducing innovations. Additional concerns: (1) Reduced consumer choice and variety, (2) Potential for price discrimination exploiting consumers, (3) Barrier to entry prevents new competitors and innovation, (4) Political influence - monopolies may lobby for favorable regulations, (5) Inequality - profit concentration in monopolist hands. These disadvantages often justify government intervention through regulation or antitrust policy.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopoly - Disadvantages: Price, Output, Efficiency Issues',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        
        // Monopolistic Competition (8 flashcards)
        {
            question: 'Define monopolistic competition and explain its key characteristics. How does product differentiation distinguish it from perfect competition?',
            answer: 'Monopolistic competition is a market structure with many firms selling differentiated products, combining elements of both monopoly and perfect competition. Key characteristics: (1) Many firms - numerous sellers but fewer than perfect competition, each with small market share, (2) Differentiated products - goods are close but not perfect substitutes, giving firms some price-making power, (3) Low barriers to entry - relatively easy for new firms to enter in long run, (4) Non-price competition - firms compete through advertising, branding, quality, and service rather than just price, (5) Independent decision-making - while firms consider competitors, there is no strategic interdependence. Product differentiation creates downward-sloping demand curves - firms can raise prices without losing all customers because products are not identical. Differentiation can be real (actual quality or features) or perceived (branding, packaging, advertising). This gives firms some monopoly power in their product niche, but competition from close substitutes limits this power. Examples: Restaurants, clothing retailers, hair salons, coffee shops.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopolistic Competition - Definition and Characteristics',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain the short-run equilibrium in monopolistic competition. Can firms make supernormal profits or losses? How is profit maximized?',
            answer: 'In the short run, monopolistically competitive firms can make supernormal profits, normal profits, or losses, similar to monopoly. The firm faces a downward-sloping demand curve due to product differentiation and maximizes profit where MC = MR. Supernormal profit scenario: When demand is strong relative to costs, the firm produces at Q* where MC = MR, charges price P* from the demand curve where P* > AC, earning supernormal profit = (P* - AC) × Q*. The profit area is a rectangle with height (P* - AC) and width Q*. Loss scenario: When demand is weak, the firm still produces where MC = MR, but price falls below AC (P < AC), creating losses. The firm continues operating if P > AVC to cover variable costs and contribute to fixed costs. Normal profit: Occurs when P = AC at the profit-maximizing output. Unlike perfect competition, firms have some control over price due to differentiated products, but face relatively elastic demand due to availability of close substitutes.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopolistic Competition - Short-run Equilibrium',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Describe the long-run equilibrium in monopolistic competition. Why do firms earn only normal profit in the long run? Explain the entry and exit mechanism.',
            answer: 'In long-run equilibrium, monopolistically competitive firms earn only normal profit (zero economic profit) where P = AC, but P > MC due to the downward-sloping demand curve. The entry/exit mechanism works as follows: If firms earn supernormal profits: (1) Low barriers attract new entrants with similar differentiated products, (2) New entry reduces each existing firm\'s market share and demand, (3) Individual firm demand curves shift left until P = AC, eliminating supernormal profits. If firms make losses: (1) Some firms exit the market, (2) Remaining firms gain market share as demand shifts right, (3) Demand curves shift until P = AC, eliminating losses. Long-run equilibrium position: (1) P = AC (zero economic profit), (2) MC = MR (profit maximization), (3) P > MC (allocative inefficiency remains), (4) Production not at minimum AC (productive inefficiency), (5) Each firm retains downward-sloping demand due to product differentiation. Unlike perfect competition, the tangency of demand and AC curves occurs on the downward-sloping portion of AC, not at minimum AC.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopolistic Competition - Long-run Equilibrium',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'What is excess capacity in monopolistic competition? Explain why firms produce to the left of minimum average cost and the efficiency implications.',
            answer: 'Excess capacity occurs when firms produce at output levels below the productively efficient scale (minimum AC). In monopolistic competition, long-run equilibrium has firms producing to the left of minimum AC on the downward-sloping portion of the AC curve, where P = AC but AC is not minimized. Why excess capacity exists: (1) Downward-sloping demand from product differentiation, (2) Zero economic profit condition (P = AC) occurs before minimum AC is reached, (3) Firms could produce more at lower unit cost but don\'t because they lack sufficient demand. Efficiency implications: (1) Productive inefficiency - firms don\'t minimize average costs, producing at higher AC than necessary, (2) Too many firms - industry could produce the same total output with fewer firms at minimum AC, (3) Resources wasted on duplicate facilities and underutilized capacity. Trade-off consideration: Excess capacity is the cost of product variety. While inefficient, it provides consumers with diverse choices and differentiated products. Society may prefer variety despite higher costs compared to standardized products at minimum AC. This distinguishes monopolistic competition from perfect competition where long-run equilibrium occurs at minimum AC.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopolistic Competition - Excess Capacity',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain allocative inefficiency in monopolistic competition. Why does producing where P > MC create welfare loss?',
            answer: 'Monopolistic competition is allocatively inefficient because firms produce where P > MC, both in short run and long run. Even in long-run equilibrium with zero economic profit, allocative inefficiency persists. Why P > MC: (1) Downward-sloping demand curve makes MR < P, (2) Profit maximization at MC = MR means MC < P, (3) Product differentiation gives firms some market power to set price above marginal cost. Welfare implications: (1) Underproduction - output is below socially optimal level where P = MC, (2) Deadweight loss triangle exists between actual output and allocatively efficient output, (3) Marginal benefit (P) exceeds marginal cost for units not produced, representing foregone gains from trade, (4) Consumer surplus is lower than under perfect competition. However, the allocative inefficiency is typically smaller than monopoly because: (1) Demand is relatively elastic due to close substitutes, (2) Multiple firms compete, limiting market power, (3) Low barriers to entry provide contestability. The welfare loss must be weighed against benefits of product variety and differentiation that consumers value.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopolistic Competition - Allocative Inefficiency',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain productive inefficiency in monopolistic competition. Why don\'t firms produce at minimum average cost in long-run equilibrium?',
            answer: 'Monopolistic competition exhibits productive inefficiency in long-run equilibrium as firms do not produce at minimum AC. Instead, they produce on the downward-sloping portion of the AC curve where AC is still declining. Reasons for productive inefficiency: (1) Downward-sloping demand curve due to product differentiation, (2) Zero profit condition (P = AC) is satisfied before reaching minimum AC, (3) Tangency point of demand and AC curves occurs left of minimum AC, (4) Insufficient demand for each firm to expand to minimum efficient scale. Technical explanation: The demand curve becomes tangent to the AC curve at an output level below minimum AC. At this point, P = AC (zero economic profit) but AC could be lower at a higher output. If the firm produced at minimum AC, P would be below AC, causing losses. Implications: (1) Higher unit costs than technically necessary, (2) Excess capacity and underutilization of resources, (3) More firms and facilities than needed for given industry output. This contrasts with perfect competition where competitive pressure and horizontal demand force firms to minimum AC in long run. The productive inefficiency is the price paid for product variety.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopolistic Competition - Productive Inefficiency',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Describe the product differentiation strategies used in monopolistic competition: branding, quality, design, and advertising. Why is non-price competition important?',
            answer: 'Firms in monopolistic competition rely heavily on product differentiation and non-price competition to attract customers and build brand loyalty. Key strategies: Branding: (1) Creating distinct brand identity and reputation, (2) Building customer loyalty and emotional connections, (3) Examples: Nike swoosh, Apple products, Starbucks coffee. Quality differentiation: (1) Superior materials, craftsmanship, or features, (2) Better customer service and warranties, (3) Examples: Premium restaurant ingredients, luxury goods. Design and innovation: (1) Unique aesthetic appeal or functionality, (2) Continuous product improvements and new variants, (3) Examples: Fashion designs, smartphone features. Advertising and marketing: (1) Informing consumers about product attributes, (2) Persuading through emotional appeals and lifestyle associations, (3) Creating perceived differences even when actual differences are minimal, (4) Examples: Television commercials, social media marketing, celebrity endorsements. Why non-price competition matters: (1) Reduces price elasticity of demand - loyal customers less responsive to competitors\' prices, (2) Shifts demand curve right - increases market share and revenue, (3) Sustains differentiation - prevents products becoming commoditized, (4) Supports premium pricing - justifies higher prices through perceived value.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopolistic Competition - Product Differentiation Strategies',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Compare monopolistic competition with perfect competition in terms of efficiency, output, prices, and consumer welfare. Discuss the trade-off between efficiency and variety.',
            answer: 'Monopolistic competition vs. Perfect competition comparison: Allocative efficiency: MC is less efficient (P > MC vs. P = MC), but gap is smaller than monopoly due to elastic demand and competition. Deadweight loss exists but is relatively small. Productive efficiency: MC is less efficient (not at minimum AC vs. at minimum AC). Excess capacity in MC means higher unit costs. More firms in MC industry than needed for given output. Prices and output: MC has higher prices and lower output per firm than PC. However, total industry variety and product options are greater in MC. Consumer welfare: MC has lower consumer surplus per product due to higher prices. However, consumers value product variety and differentiation, which PC lacks. Availability of choices and tailored products may offset higher prices. The fundamental trade-off: Efficiency loss vs. variety gain. Perfect competition achieves maximum efficiency but offers homogeneous products. Monopolistic competition sacrifices some efficiency for product diversity that consumers value. Whether society is better off depends on consumer preferences for variety versus lower prices. In reality, most consumer goods markets resemble monopolistic competition, suggesting consumers value differentiation despite efficiency costs.',
            level: 'JC',
            category: 'Economics',
            topic: 'Monopolistic Competition - Comparison with Perfect Competition',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        
        // Oligopoly (8 flashcards)
        {
            question: 'Define oligopoly and explain its key characteristics. What is meant by strategic interdependence and why is it crucial to oligopolistic behavior?',
            answer: 'Oligopoly is a market structure with a few dominant firms that have significant market power and exhibit strategic interdependence. Key characteristics: (1) Few dominant firms - typically 3-10 firms control majority of market share, (2) Concentrated market - high concentration ratios, (3) Interdependence - each firm\'s decisions significantly affect rivals and vice versa, (4) Barriers to entry - substantial obstacles prevent new competition (economies of scale, brand loyalty, capital requirements), (5) Product homogeneity or differentiation - can be standardized (steel, oil) or differentiated (automobiles, electronics). Strategic interdependence is the defining feature: Each firm must consider rivals\' likely reactions when making decisions about price, output, advertising, or product changes. Firms are mutually aware and responsive to each other\'s actions. Decisions involve game theory - anticipating competitors\' strategies and best responses. This creates uncertainty and complex decision-making unlike other market structures. Examples: Automobile industry, telecommunications, airlines, soft drinks, banking. The interdependence can lead to both competitive and cooperative behavior, making oligopoly outcomes less predictable than other market structures.',
            level: 'JC',
            category: 'Economics',
            topic: 'Oligopoly - Definition and Strategic Interdependence',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain the kinked demand curve model for oligopoly. Why does it predict price rigidity? Describe the MR curve discontinuity and its implications.',
            answer: 'The kinked demand curve model explains price rigidity in oligopoly based on asymmetric rival reactions to price changes. Model assumptions: If a firm raises price above current level: Rivals will not follow (keep their prices constant), so the firm loses substantial market share to competitors. Demand is relatively elastic above current price. If a firm lowers price below current level: Rivals will match the price cut to maintain market share, so the firm gains little market share. Demand is relatively inelastic below current price. Resulting demand curve: Kinked at current price P* - elastic (flat) above the kink, inelastic (steep) below the kink. The kink represents the current price-quantity combination. MR curve discontinuity: The corresponding MR curve has a vertical discontinuity (gap) at the kink output level. MC can shift within this discontinuous range without changing optimal price or quantity. This explains price rigidity - even with cost changes, the firm maintains price at P* as long as MC remains in the discontinuous range. Limitations: (1) Doesn\'t explain how P* was initially determined, (2) Assumes specific reaction patterns that may not hold, (3) Doesn\'t explain price leadership or coordination.',
            level: 'JC',
            category: 'Economics',
            topic: 'Oligopoly - Kinked Demand Curve Model',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain collusion in oligopoly markets. Compare explicit collusion (cartels) with tacit collusion (price leadership). How do colluding firms maximize joint profits?',
            answer: 'Collusion occurs when oligopolistic firms cooperate to reduce competition and increase joint profits, acting like a shared monopoly. Explicit collusion (cartels): Formal agreements to coordinate prices, output, or market sharing. Firms meet and negotiate terms explicitly. Example: OPEC (Organization of Petroleum Exporting Countries) coordinates oil production and prices among member nations. Usually illegal in most countries due to antitrust laws. Members agree to restrict output and charge monopoly prices. Tacit collusion (price leadership): Informal coordination without explicit communication. One dominant firm (price leader) sets prices and others follow. Types: Dominant firm leadership (largest firm leads), Barometric leadership (most reliable firm leads based on market conditions). Example: Airlines often follow pricing of major carriers. Legal in most jurisdictions as no explicit agreement exists. Joint profit maximization: Colluding firms act as a multi-plant monopoly: (1) Determine market demand and aggregate MC, (2) Find profit-maximizing output where industry MC = MR, (3) Set monopoly price above MC, (4) Allocate production quotas among members, often based on market share or capacity. Result: Higher prices, lower output than competition, monopoly-level profits split among members, deadweight loss to society.',
            level: 'JC',
            category: 'Economics',
            topic: 'Oligopoly - Collusion: Explicit vs Tacit',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'What conditions make collusion more likely to succeed in oligopoly? Explain why these factors facilitate cooperation and monitoring among firms.',
            answer: 'Successful collusion requires conditions that enable agreement, monitoring, and enforcement among oligopolistic firms: Few firms: (1) Easier to negotiate and coordinate with fewer parties, (2) Lower transaction costs of organizing collusion, (3) Each firm\'s compliance is more visible and important, (4) Less chance of disagreement over terms. Similar cost structures: (1) Firms agree more easily on prices and output levels, (2) Reduces conflicts over who produces what quantities, (3) Low-cost firms less tempted to cheat by undercutting prices, (4) Fair distribution of quotas more achievable. Stable and predictable demand: (1) Easier to maintain agreed prices without frequent adjustments, (2) Less temptation to cheat during demand fluctuations, (3) Reduces uncertainty that could trigger competitive behavior, (4) Members can detect deviations from agreements more easily. Effective monitoring mechanisms: (1) Ability to observe rivals\' prices and output, (2) Transparent market information prevents secret price cuts, (3) Industry associations facilitate information sharing, (4) Penalties for non-compliance are credible. Favorable legal environment: (1) Weak antitrust enforcement or legal exemptions, (2) Government support or tolerance of coordination, (3) International cartels harder to prosecute. High barriers to entry: (1) Prevents new entrants from undermining collusive agreements, (2) Protects supernormal profits from being competed away.',
            level: 'JC',
            category: 'Economics',
            topic: 'Oligopoly - Conditions for Successful Collusion',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Why is collusion often unstable in oligopoly? Explain the incentive to cheat and use the prisoner\'s dilemma to illustrate this instability.',
            answer: 'Collusion faces inherent instability due to individual incentives to cheat despite collective benefits from cooperation. Incentive to cheat: While all firms benefit from maintaining high collusive prices, each individual firm can gain more by secretly undercutting the agreed price while others maintain high prices. The cheating firm captures market share from rivals while charging only slightly lower prices, significantly increasing profits. If all firms cheat, they end up in competitive outcome with lower profits for all. Prisoner\'s dilemma illustration: Two firms can collude (cooperate) or compete (cheat). Payoff matrix shows: If both collude: Each earns moderate profits (e.g., $50 million each). If one cheats while other colludes: Cheater earns high profits ($80 million), cooperator earns low profits ($20 million). If both cheat: Each earns low competitive profits ($30 million each). Dominant strategy is to cheat regardless of rival\'s action, leading to Nash equilibrium where both cheat despite joint outcome being worse than collusion. This explains why cartels frequently break down. Detection and punishment challenges: (1) Secret price cuts are hard to detect immediately, (2) Delays in punishment allow cheaters to benefit, (3) Punishment (price wars) hurts all firms, (4) External factors (demand shifts, new entrants) destabilize agreements.',
            level: 'JC',
            category: 'Economics',
            topic: 'Oligopoly - Instability of Collusion and Prisoner\'s Dilemma',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain game theory concepts in oligopoly: prisoner\'s dilemma, Nash equilibrium, and dominant strategy. How do these explain oligopolistic behavior?',
            answer: 'Game theory analyzes strategic interactions in oligopoly where outcomes depend on all firms\' choices. Key concepts: Prisoner\'s dilemma: Classic game illustrating conflict between individual rationality and collective benefit. Each player has incentive to defect (cheat) regardless of other\'s action, leading to worse outcome for both than mutual cooperation. In oligopoly: Represents tension between collusion (cooperate) and competition (cheat). Both firms better off colluding, but individual incentive to undercut leads to competitive outcome. Nash equilibrium: Outcome where no player can improve their payoff by unilaterally changing strategy, given others\' strategies. Each player\'s strategy is best response to others\' strategies. In oligopoly: Represents stable outcome such as both firms competing. Neither firm wants to change behavior given rival\'s strategy, even though both would benefit from coordinated collusion. Can result in suboptimal outcomes. Dominant strategy: A strategy that yields highest payoff regardless of what rivals do. Player always chooses this strategy in rational play. In oligopoly prisoner\'s dilemma: Cheating is dominant strategy as it yields higher profit whether rival colludes or cheats. Leads inevitably to competitive Nash equilibrium. These concepts explain: Why collusion is difficult to maintain, How strategic thinking influences pricing and output decisions, Why oligopolies may settle into stable competitive patterns.',
            level: 'JC',
            category: 'Economics',
            topic: 'Oligopoly - Game Theory: Nash Equilibrium and Dominant Strategy',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Describe non-collusive oligopoly behavior. Explain price wars and non-price competition strategies like advertising and product development.',
            answer: 'When collusion fails or is not attempted, oligopolistic firms engage in various competitive strategies: Price wars: Intense price competition where firms repeatedly undercut each other\'s prices. Triggers: One firm cuts price to gain market share, rivals match or beat the cut, escalating downward spiral. Consequences: Profits erode for all firms, prices approach competitive levels, may lead to losses and exit. Resolution: Firms recognize mutual harm and implicitly coordinate on higher stable prices, or one firm exits reducing competition. Examples: Airline fare wars, retail gasoline price competitions, supermarket discounting. Non-price competition: Firms avoid direct price competition and instead compete through: Advertising and marketing: (1) Building brand loyalty and differentiation, (2) Informing consumers about products, (3) Creating barriers to entry through established brands, (4) Example: Coca-Cola vs. Pepsi advertising campaigns. Product development and innovation: (1) Introducing new features or improved products, (2) Technological advancement and R&D investment, (3) Creating temporary competitive advantages, (4) Example: Smartphone manufacturers\' annual new model releases. Quality improvements: Enhancing product quality, reliability, or customer service. Customer relationship management: Loyalty programs, personalized service, after-sales support. Strategic advantages of non-price competition: (1) Less likely to trigger immediate retaliation than price cuts, (2) Can create sustainable competitive advantages, (3) Maintains higher profit margins than price competition.',
            level: 'JC',
            category: 'Economics',
            topic: 'Oligopoly - Non-collusive Behavior: Price Wars and Non-price Competition',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Compare oligopoly outcomes under collusive versus non-collusive behavior. How do these outcomes differ in terms of prices, output, efficiency, and welfare compared to monopoly and perfect competition?',
            answer: 'Oligopoly outcomes vary significantly depending on whether firms collude or compete: Collusive oligopoly (cartel): Approximates monopoly outcomes: Price and output: Firms restrict output and charge monopoly prices (Pm, Qm). Prices are high, output low relative to competition. Efficiency: Allocatively inefficient (P > MC), productively inefficient depending on cost structure, significant deadweight loss. Welfare: Low consumer surplus, high producer surplus for cartel members, similar to monopoly. Stability: Unstable due to cheating incentives. Competitive (non-collusive) oligopoly: Outcomes between monopoly and perfect competition depending on intensity of competition: Price and output: Prices lower than monopoly but higher than perfect competition. Output greater than monopoly but less than perfect competition. Efficiency: Moderate allocative inefficiency (P > MC but gap smaller than monopoly), productive efficiency varies, smaller deadweight loss than monopoly. Welfare: Higher consumer surplus than monopoly, lower producer surplus, better total welfare than monopoly. Stability: More stable if firms settle into Nash equilibrium. Comparison summary: Perfect Competition: P = MC, maximum efficiency and welfare. Competitive Oligopoly: P > MC but closer to PC, moderate efficiency. Collusive Oligopoly: Similar to monopoly, P >> MC, lowest efficiency. Monopoly: P >> MC, maximum inefficiency and deadweight loss. Real-world oligopolies typically oscillate between collusive and competitive behavior, producing outcomes in the middle range.',
            level: 'JC',
            category: 'Economics',
            topic: 'Oligopoly - Comparing Collusive vs Competitive Outcomes',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        
        // Comparing Market Structures (4 flashcards)
        {
            question: 'Compare allocative efficiency across the four main market structures: perfect competition, monopolistic competition, oligopoly, and monopoly. Rank them from most to least efficient and explain why.',
            answer: 'Allocative efficiency ranking from most to least efficient: 1. Perfect Competition (Most efficient): Produces where P = MC in long run, achieving allocative efficiency. No deadweight loss. Resources allocated optimally with marginal benefit equal to marginal cost. Maximum total surplus. 2. Monopolistic Competition: P > MC in both short and long run due to downward-sloping demand. Small deadweight loss due to relatively elastic demand and competition from close substitutes. Gap between P and MC is moderate as firms have limited market power. 3. Oligopoly (varies by behavior): Competitive oligopoly: P > MC but extent depends on degree of competition. Deadweight loss moderate to large. Closer to monopolistic competition when competitive, closer to monopoly when collusive. Collusive oligopoly: Similar to monopoly with P >> MC and large deadweight loss as firms act as shared monopoly. 4. Monopoly (Least efficient): P >> MC with largest deadweight loss. Most severe allocative inefficiency as monopolist restricts output significantly below socially optimal level. Substantial foregone welfare due to underconsumption. Key insight: The greater the firm\'s market power (ability to set price above MC), the worse the allocative inefficiency. Competitive pressure improves allocative efficiency by constraining pricing power.',
            level: 'JC',
            category: 'Economics',
            topic: 'Comparing Market Structures - Allocative Efficiency Ranking',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Compare dynamic efficiency across market structures. Why might monopoly and oligopoly have advantages over perfect competition in innovation and technological progress despite static inefficiencies?',
            answer: 'Dynamic efficiency refers to innovation and technological advancement over time, potentially offsetting static allocative and productive inefficiencies. Monopoly and oligopoly advantages: Ability to innovate: (1) Supernormal profits provide financial resources for R&D investment, (2) Large firm size enables economies of scale in research, (3) Can afford risky long-term projects with uncertain returns, (4) Example: Pharmaceutical monopolies investing billions in drug development. Incentive to innovate: (1) Prospect of monopoly profits from successful innovation motivates R&D, (2) Patents and intellectual property protection guarantee returns on innovation, (3) Need to maintain market position drives product improvements in oligopoly, (4) Example: Technology firms like Apple and Samsung competing through innovation. Schumpeterian view: Monopoly profits are necessary for capitalism\'s creative destruction process. Temporary monopolies from innovation drive economic progress, more important than static efficiency losses. Perfect competition limitations: (1) Zero economic profits leave no funds for R&D, (2) Small firm size limits research capacity, (3) Cannot appropriate returns from innovation as competitors quickly imitate, (4) Short-term focus on survival prevents long-term investment. Counterarguments: Monopolies may lack incentive to innovate due to comfortable position, X-inefficiency reduces innovation effectiveness, Competitive pressure may spur innovation more than monopoly comfort. Conclusion: Trade-off between static efficiency and dynamic efficiency. Optimal market structure may involve some market power to incentivize innovation.',
            level: 'JC',
            category: 'Economics',
            topic: 'Comparing Market Structures - Dynamic Efficiency',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Compare consumer welfare across market structures considering price levels, output quantities, product variety, and quality. Which structure best serves consumer interests?',
            answer: 'Consumer welfare comparison across dimensions: Price levels (lower is better): Perfect Competition: Lowest prices (P = MC), best for consumers. Monopolistic Competition: Moderate prices, premium for differentiation. Oligopoly: Varies - competitive behavior yields moderate prices, collusion yields high monopoly-like prices. Monopoly: Highest prices (P >> MC), worst for consumers. Output quantities (higher is better): Perfect Competition: Highest output at socially optimal level. Monopolistic Competition: Moderate output per firm, but many firms and products. Oligopoly: Lower than perfect competition, varies by competitiveness. Monopoly: Lowest output, significant restriction. Product variety and choice: Perfect Competition: No variety, homogeneous products only. Monopolistic Competition: Greatest variety and differentiation, wide consumer choice. Oligopoly: Moderate to high variety depending on non-price competition. Monopoly: Limited variety, single product or limited range. Quality considerations: Perfect Competition: Standardized quality, no differentiation incentive. Monopolistic Competition: Quality differentiation common, competition on quality. Oligopoly: High quality possible through non-price competition and innovation. Monopoly: Quality variable - may be low due to lack of competition, or high if reputation matters. Overall assessment: Perfect Competition best for low prices and high output. Monopolistic Competition best for variety and choice despite higher prices. Oligopoly and Monopoly generally worse for consumers except potentially for innovation. Consumer preferences matter - some value low prices (favor PC), others value variety and innovation (may tolerate market power).',
            level: 'JC',
            category: 'Economics',
            topic: 'Comparing Market Structures - Consumer Welfare',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain contestable markets theory. How can potential competition from hit-and-run entry discipline even monopolistic market structures? What conditions make markets contestable?',
            answer: 'Contestable markets theory suggests that potential competition can discipline firms even in concentrated markets, making entry threats as important as actual competition. Core concept: If entry and exit are costless, potential entrants can engage in hit-and-run entry - enter market, undercut incumbent prices to capture profits, then exit before incumbent responds. This threat constrains incumbent pricing even with monopoly structure. Key insight: Market structure (number of firms) may be less important than contestability (ease of entry/exit) in determining outcomes. How hit-and-run entry works: (1) Incumbent charges monopoly price above AC, earning supernormal profits, (2) Potential entrant identifies profit opportunity, (3) Entrant enters rapidly with lower price, capturing market share and profits, (4) Entrant exits before incumbent can respond or before retaliation, (5) Threat of this process forces incumbent to charge competitive prices even without actual entry. Conditions for contestable markets: (1) No sunk costs - all capital invested can be recovered on exit (reversible entry), (2) Free entry and exit - no legal, technical, or strategic barriers, (3) Fast entry and exit - hit-and-run possible before incumbent responds, (4) No incumbent advantages - entrants have access to same technology and costs. Examples: Airline routes with no hub investments (can redeploy planes), trucking services, some online platforms. Implications: Even single-firm markets can be competitive if perfectly contestable. Policy should focus on reducing entry barriers rather than just breaking up monopolies. Limitations: Pure contestability rarely exists - most industries have some sunk costs, incumbent advantages, and entry delays.',
            level: 'JC',
            category: 'Economics',
            topic: 'Comparing Market Structures - Contestable Markets Theory',
            difficulty: null,
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    await db.insert(flashcards).values(sampleFlashcards);
    
    console.log('✅ Flashcards seeder completed successfully - 40 comprehensive JC Microeconomics Market Structure flashcards created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});