import { db } from '@/db';
import { flashcards } from '@/db/schema';

async function main() {
    const sampleFlashcards = [
        // Perfect Competition (10 cards)
        {
            question: 'What are the four key characteristics of a perfectly competitive market?',
            answer: '1. Many buyers and sellers - each firm is a price taker with no market power\n2. Homogeneous products - goods are perfect substitutes, no product differentiation\n3. No barriers to entry or exit - firms can freely enter or leave the market in the long run\n4. Perfect information - all market participants have complete knowledge of prices, costs, and product quality',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain why a perfectly competitive firm is a price taker.',
            answer: 'A perfectly competitive firm is a price taker because:\n1. It produces a homogeneous product that is a perfect substitute for competitors\' products\n2. It represents a negligible fraction of total market supply\n3. Individual firms cannot influence market price through output decisions\n4. The firm faces a perfectly elastic demand curve at the market price\n5. Any attempt to raise price above market equilibrium results in zero sales as consumers switch to identical competitors\' products',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Using a diagram, explain how a perfectly competitive firm determines its profit-maximizing output in the short run.',
            answer: 'A perfectly competitive firm maximizes profit where MC=MR:\n\n1. The firm faces a horizontal demand curve (AR=MR) at market price P\n2. Profit is maximized at output Q* where MC=MR\n3. At Q*, the vertical distance between AR and AC represents per-unit profit\n4. Total profit = (AR-AC) × Q*\n\nThree possible outcomes:\n- Supernormal profit: P > AC at Q* (firm earns above normal returns)\n- Normal profit: P = AC at Q* (firm covers all opportunity costs)\n- Subnormal profit (loss): P < AC at Q* (firm should continue if P > AVC to cover some fixed costs)',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the adjustment process from short-run supernormal profits to long-run equilibrium in perfect competition.',
            answer: 'The adjustment mechanism:\n\n1. Short-run: Existing firms earn supernormal profits (P > AC)\n2. Perfect information allows potential entrants to observe these profits\n3. Absence of barriers enables new firms to enter the market\n4. Entry increases market supply, shifting supply curve rightward\n5. Market price falls due to increased supply\n6. Process continues until P = AC (minimum point)\n7. Long-run equilibrium: firms earn only normal profit, no incentive for further entry or exit\n\nReverse process occurs if firms make subnormal profits - exit reduces supply, raising price until normal profit is restored.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What is allocative efficiency and why is it achieved in perfect competition?',
            answer: 'Allocative efficiency occurs when P = MC, meaning resources are allocated to produce the combination of goods most valued by society.\n\nIn perfect competition:\n1. Firms produce where MC = MR\n2. For price takers, MR = AR = P\n3. Therefore, P = MC at equilibrium\n4. This means the price consumers pay (reflecting marginal benefit) equals the marginal cost of production\n5. Society\'s valuation of the last unit equals the opportunity cost of resources used\n6. No reallocation of resources can improve social welfare\n\nAllocative efficiency maximizes total economic surplus (consumer + producer surplus).',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain productive efficiency and its achievement in perfect competition.',
            answer: 'Productive efficiency occurs when production takes place at minimum average cost (P = MC = AC at minimum AC).\n\nIn perfect competition:\n1. Long-run equilibrium requires P = AC (no supernormal profits)\n2. Profit maximization requires P = MC\n3. Therefore, at equilibrium: P = MC = AC\n4. This only occurs at the minimum point of the AC curve\n5. Firms produce at the most technically efficient scale\n6. No wastage of resources - output is produced at lowest possible cost per unit\n\nProductive efficiency means society gets maximum output from given resources.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Why do perfectly competitive firms produce at the minimum point of their AC curve in the long run?',
            answer: 'Long-run production at minimum AC results from market forces:\n\n1. Free entry/exit ensures P = AC in long run (normal profit only)\n2. Profit maximization requires MC = MR = P\n3. Combining these conditions: P = MC = AC\n4. This equality only holds at minimum AC\n\nIf firm produces below minimum AC:\n- MC < AC, so producing more reduces average cost\n- Competition forces expansion to remain viable\n\nIf firm produces above minimum AC:\n- MC > AC, so reducing output lowers average cost\n- Competitive pressure drives output reduction\n\nOnly at minimum AC is there no competitive pressure to change output.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What is the shutdown condition for a perfectly competitive firm in the short run?',
            answer: 'A firm should shutdown if P < AVC (price falls below average variable cost).\n\nReasoning:\n1. Fixed costs exist regardless of production (rent, machinery depreciation)\n2. If P > AVC: Firm covers variable costs and contributes to fixed costs\n3. If P < AVC: Firm cannot cover even variable costs - losses exceed fixed costs\n4. Better to shutdown temporarily and only lose fixed costs\n\nContinuation rule: Operate if P ≥ AVC (even with losses) because:\n- Revenue covers all variable costs\n- Some contribution toward fixed costs\n- Losses smaller than shutting down\n\nIn long run, firm must achieve P ≥ AC or exit permanently.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain why the supply curve of a perfectly competitive firm is its MC curve above minimum AVC.',
            answer: 'The firm\'s supply curve shows quantity supplied at each price:\n\n1. Profit maximization occurs where P = MC\n2. For each price level, firm supplies quantity where P intersects MC\n3. Below minimum AVC, firm shuts down (zero supply)\n4. Therefore, supply curve = MC curve above minimum AVC\n\nKey points:\n- At any P > minimum AVC: firm operates and supplies Q where P = MC\n- At P < minimum AVC: firm supplies zero (shutdown)\n- Minimum AVC is the shutdown point\n\nMarket supply = horizontal summation of all firms\' MC curves above minimum AVC.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Discuss whether perfect competition is realistic and provide real-world examples that approximate this market structure.',
            answer: 'Perfect competition is largely theoretical, but some markets approximate it:\n\nClose approximations:\n1. Agricultural commodities (wheat, rice, corn) - many farmers, homogeneous products\n2. Financial markets (foreign exchange, stock markets) - many traders, standardized products, near-perfect information\n3. Online marketplaces for commodity goods - low barriers, price transparency\n\nWhy most markets deviate:\n1. Product differentiation common (branding, quality differences)\n2. Barriers to entry exist (capital requirements, regulations, patents)\n3. Information asymmetries prevalent\n4. Many markets have few dominant firms (oligopoly)\n\nImportance despite unrealism:\n- Provides benchmark for efficiency\n- Shows benefits of competition\n- Guides competition policy\n- Helps analyze real market structures',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Monopoly (10 cards)
        {
            question: 'What are the key characteristics of a monopoly market structure?',
            answer: '1. Single seller (price setter) - firm has complete market power and faces the entire market demand curve\n2. Unique product with no close substitutes - high cross elasticity with other goods\n3. High barriers to entry - prevents new firms from entering market\n4. Imperfect information - consumers may not know about alternatives or true costs\n5. Price discrimination possible - firm can charge different prices to different consumers\n\nAs sole supplier, monopolist can influence price by adjusting quantity, unlike perfect competition where firms are price takers.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the different types of barriers to entry that create and sustain monopolies.',
            answer: 'Natural barriers:\n1. Economies of scale - incumbent has cost advantage, making entry unprofitable\n2. Control of essential resources - monopolist owns key inputs (e.g., De Beers and diamonds)\n3. Network effects - value increases with users (e.g., social media platforms)\n\nArtificial barriers:\n1. Legal barriers - patents, copyrights, licenses protect intellectual property\n2. Strategic barriers - predatory pricing, limit pricing deter entry\n3. Government regulations - exclusive franchises, statutory monopolies\n\nFinancial barriers:\n1. High capital requirements - large sunk costs deter entry\n2. Brand loyalty - established reputation difficult to overcome\n\nThese barriers prevent contestability and allow supernormal profits to persist long-term.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Using a diagram, explain how a monopolist determines price and output to maximize profit.',
            answer: 'Monopoly profit maximization:\n\n1. Monopolist faces downward-sloping demand curve (AR)\n2. MR curve lies below AR (MR < AR for all Q > 0)\n3. Profit maximized where MC = MR at quantity Q*\n4. Price determined by AR curve at P* (above MC)\n5. Supernormal profit = (P* - AC) × Q*\n\nKey differences from perfect competition:\n- P > MC (allocative inefficiency)\n- P > AC at profit-maximizing output (supernormal profit persists)\n- Output lower and price higher than competitive market\n- Dead weight loss created (consumer surplus becomes lost surplus)\n\nMonopolist restricts output to raise price above competitive level.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the three degrees of price discrimination with examples.',
            answer: 'First-degree (perfect) price discrimination:\n- Charge each consumer their maximum willingness to pay\n- Extracts all consumer surplus\n- Example: Personalized pricing algorithms, professional services\n- Requires perfect information about individual preferences\n\nSecond-degree price discrimination:\n- Charge different prices based on quantity consumed\n- Self-selection by consumers\n- Examples: Bulk discounts, quantity-based pricing tiers\n- Block tariffs in utilities (electricity)\n\nThird-degree price discrimination:\n- Charge different prices to different consumer groups\n- Based on identifiable characteristics (age, location, time)\n- Examples: Student discounts, senior citizen rates, peak/off-peak pricing\n- Requires market segmentation and ability to prevent resale',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What conditions are necessary for successful price discrimination?',
            answer: 'Three essential conditions:\n\n1. Market power - firm must be price maker, not price taker\n   - Able to influence price through output decisions\n   - Faces downward-sloping demand curve\n\n2. Market segmentation - ability to identify and separate consumers\n   - Different price elasticities of demand between groups\n   - Observable characteristics (age, location, time of purchase)\n   - Willingness to pay varies across segments\n\n3. Prevention of resale (arbitrage)\n   - Consumers in low-price segment cannot resell to high-price segment\n   - Services easier than goods (cannot resell haircut)\n   - Geographic separation, time-limited offers\n   - Legal restrictions on resale\n\nWithout these conditions, price discrimination breaks down as consumers migrate to lowest-price segment.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain why monopolies are allocatively inefficient.',
            answer: 'Allocative inefficiency in monopoly:\n\n1. Condition for allocative efficiency: P = MC\n2. Monopoly equilibrium: MC = MR, but P > MC\n3. At monopoly output, P > MC means:\n   - Consumer valuation (P) exceeds cost of production (MC)\n   - Society values additional units more than their production cost\n   - Too little output produced from society\'s perspective\n\n4. Deadweight loss created:\n   - Transactions that would benefit both parties don\'t occur\n   - Potential gains from trade lost\n   - Neither consumer nor producer surplus\n\n5. Monopolist restricts output to maintain high price\n   - Reduces consumer surplus\n   - Transfers surplus from consumers to producer\n   - Net loss to society (deadweight loss)\n\nResource misallocation reduces total economic welfare.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain productive inefficiency in monopoly markets.',
            answer: 'Monopolies exhibit productive inefficiency:\n\n1. Definition: Production not at minimum AC (P ≠ minimum AC)\n\n2. Monopoly characteristics:\n   - Produces where MC = MR (profit maximization)\n   - No competitive pressure to minimize costs\n   - Barriers prevent entry of more efficient firms\n   - May not operate at minimum efficient scale\n\n3. Compared to perfect competition:\n   - Perfect competition: P = MC = minimum AC (long run)\n   - Monopoly: P > AC but not necessarily at minimum AC\n   - Higher costs per unit possible\n\n4. Implications:\n   - Resources not used most efficiently\n   - Could produce same output at lower cost\n   - Society gets less output from given resources\n   - Excess capacity may exist\n\nLack of competitive discipline allows cost inefficiency.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What is X-inefficiency and why does it occur in monopolies?',
            answer: 'X-inefficiency (organizational slack):\n\nDefinition:\n- Failure to minimize costs for given output level\n- Operating inside production possibility frontier\n- Avoidable waste and inefficiency\n\nCauses in monopolies:\n1. Lack of competitive pressure - no threat of losing market share\n2. Secure supernormal profits - no urgency to cut costs\n3. Managerial slack - satisficing rather than profit maximizing\n4. Bureaucratic inefficiencies - complex organizations, poor incentives\n5. Principal-agent problem - managers don\'t face full cost of inefficiency\n\nManifestations:\n- Excessive staffing\n- Lavish perks and expenses\n- Outdated production methods\n- Slow adoption of innovations\n- Inefficient procurement\n\nContrast with competitive markets where inefficient firms exit.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Compare and contrast consumer surplus under perfect competition and monopoly.',
            answer: 'Consumer surplus comparison:\n\nPerfect Competition:\n1. Price = MC at competitive equilibrium Pc\n2. Output Qc where supply meets demand\n3. Large consumer surplus (area below demand, above Pc)\n4. Allocatively efficient - maximum total surplus\n\nMonopoly:\n1. Price Pm > MC at monopoly equilibrium\n2. Output Qm < Qc (restricted output)\n3. Reduced consumer surplus:\n   - Lost to higher price (transfer to producer)\n   - Lost as deadweight loss (no one receives)\n4. Net welfare loss to society\n\nChanges from competition to monopoly:\n- Consumer surplus decreases\n- Producer surplus increases (but less than consumer loss)\n- Deadweight loss created\n- Total economic welfare falls\n\nSome consumer surplus transferred to monopolist as profit, but overall surplus reduced.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Evaluate whether monopolies can have beneficial effects on society despite their inefficiencies.',
            answer: 'Potential benefits of monopolies:\n\n1. Economies of scale (natural monopolies):\n   - Single firm more efficient than multiple firms\n   - Lower AC benefits consumers despite market power\n   - Examples: utilities (water, electricity networks)\n\n2. Innovation and R&D:\n   - Supernormal profits fund research\n   - Patent protection incentivizes innovation\n   - Dynamic efficiency gains may exceed static losses\n   - Examples: Pharmaceutical companies\n\n3. International competitiveness:\n   - Large domestic firms compete globally\n   - Economies of scale and scope\n   - National champions strategy\n\n4. Price discrimination benefits:\n   - Can increase output beyond simple monopoly\n   - Makes goods accessible to low-income consumers\n   - May serve markets otherwise unprofitable\n\nDrawbacks:\n- Static inefficiencies (allocative, productive, X-inefficiency)\n- Reduced consumer surplus\n- No guarantee profits fund innovation\n- May stifle competition and new entrants\n\nConclusion: Case-by-case evaluation needed, considering industry characteristics and regulatory framework.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Monopolistic Competition (8 cards)
        {
            question: 'What are the key characteristics of monopolistic competition?',
            answer: '1. Many firms - each firm has small market share, no single firm dominates\n2. Product differentiation - goods are similar but not identical (substitutes but not perfect)\n3. Low barriers to entry/exit - relatively easy for new firms to enter\n4. Some price-making power - due to differentiation, but limited by substitutes\n5. Non-price competition important - advertising, branding, quality\n\nExamples: Restaurants, clothing retailers, hairdressers, coffee shops\n\nDiffers from perfect competition: Product differentiation and branding\nDiffers from monopoly: Many firms, low barriers, close substitutes available\n\nFirms face downward-sloping demand curves but more elastic than monopoly due to substitutes.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the short-run equilibrium in monopolistic competition.',
            answer: 'Short-run equilibrium:\n\n1. Firm maximizes profit where MC = MR\n2. Price determined by AR curve (above MR)\n3. Possible outcomes:\n   - Supernormal profit if P > AC\n   - Normal profit if P = AC\n   - Loss if P < AC (but continue if P > AVC)\n\n4. Key features:\n   - Firm acts like monopolist in short run\n   - Has some price-making power due to differentiation\n   - P > MC (allocative inefficiency)\n   - May not produce at minimum AC\n\n5. Supernormal profits attract entry:\n   - No significant barriers\n   - New firms enter with differentiated products\n   - Triggers adjustment to long-run equilibrium\n\nSimilar to monopoly short-run but entry possible.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the adjustment from short-run to long-run equilibrium in monopolistic competition.',
            answer: 'Adjustment process when supernormal profits exist:\n\n1. Short run: Existing firms earn supernormal profits (P > AC)\n\n2. Entry occurs:\n   - Low barriers allow new firms to enter\n   - New entrants offer differentiated products\n   - Market becomes more crowded\n\n3. Effect of entry:\n   - Each firm\'s demand curve shifts left (smaller market share)\n   - Demand becomes more elastic (more substitutes available)\n   - Reduces each firm\'s price and quantity\n\n4. Long-run equilibrium:\n   - Entry continues until P = AC (normal profit only)\n   - No incentive for further entry or exit\n   - Each firm produces where MC = MR and P = AC\n   - AR curve tangent to AC curve\n\n5. Firms earn only normal profit but maintain product differentiation and brand loyalty.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What is excess capacity in monopolistic competition and why does it occur?',
            answer: 'Excess capacity:\n\nDefinition:\n- Firm produces below minimum efficient scale (minimum AC)\n- Could produce more at lower average cost\n- Plant underutilized relative to productive efficiency\n\nWhy it occurs:\n1. Long-run equilibrium: P = AC but P > MC\n2. AR tangent to AC on downward-sloping portion\n3. Not at minimum AC point (unlike perfect competition)\n4. To produce at minimum AC would require P < AC (losses)\n\nImplications:\n1. Productive inefficiency - not producing at lowest cost per unit\n2. Society gets less output than technically feasible\n3. Could serve more customers at lower price\n4. Trade-off: excess capacity vs. product variety\n\nExcess capacity is the "cost" of product differentiation and consumer choice.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Compare the efficiency outcomes of monopolistic competition with perfect competition.',
            answer: 'Allocative efficiency:\n- Perfect competition: P = MC ✓ (allocatively efficient)\n- Monopolistic competition: P > MC ✗ (allocatively inefficient)\n- Deadweight loss exists but smaller than monopoly\n\nProductive efficiency:\n- Perfect competition: P = minimum AC ✓ (long run)\n- Monopolistic competition: P > minimum AC ✗ (excess capacity)\n- Firms don\'t minimize costs per unit\n\nX-efficiency:\n- Both face competitive pressure (free entry)\n- Monopolistic competition: Less pressure than perfect competition\n- Some organizational slack possible\n\nDynamic efficiency:\n- Monopolistic competition may invest more in product development\n- Innovation and differentiation rewarded\n- Product variety benefits consumers\n\nTrade-off: Static inefficiency vs. product diversity and consumer choice',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain why advertising and branding are particularly important in monopolistic competition.',
            answer: 'Importance of advertising and branding:\n\n1. Create product differentiation:\n   - Distinguish product from close substitutes\n   - Build perceived uniqueness\n   - Develop brand loyalty\n\n2. Shift demand curve:\n   - Rightward shift increases market share\n   - Make demand less elastic (reduce substitutability)\n   - Allow higher prices without losing all customers\n\n3. Overcome competition:\n   - Many similar products available\n   - Non-price competition crucial\n   - Quality signals to consumers\n\n4. Create barriers to entry:\n   - Established brands harder to challenge\n   - New entrants need significant marketing investment\n   - Customer loyalty reduces contestability\n\nTrade-offs:\n- Costs increase AC (reducing consumer welfare)\n- May provide information (beneficial)\n- Can create artificial differentiation (persuasive advertising)',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Discuss whether excess capacity in monopolistic competition represents market failure.',
            answer: 'Arguments that excess capacity is market failure:\n\n1. Productive inefficiency:\n   - Firms don\'t minimize AC\n   - Resources wasted producing below optimal scale\n   - Higher prices than necessary\n\n2. Allocative inefficiency:\n   - P > MC means underproduction\n   - Deadweight loss created\n   - Could improve welfare by increasing output\n\n3. Duplicated facilities:\n   - Too many firms with underutilized capacity\n   - Could consolidate for efficiency\n\nArguments against market failure view:\n\n1. Product variety benefits:\n   - Consumers value choice and differentiation\n   - Willing to pay premium for preferred brands\n   - Utility from variety exceeds cost of inefficiency\n\n2. Innovation incentive:\n   - Differentiation drives product development\n   - Dynamic efficiency gains\n   - Competition through quality\n\n3. No pure waste:\n   - Differentiation serves consumer preferences\n   - Reflects genuine demand for variety\n\nConclusion: Trade-off between static efficiency and product diversity - not necessarily market failure.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Provide real-world examples of monopolistic competition and explain how they exhibit the key characteristics.',
            answer: 'Restaurant industry:\n- Many restaurants in any city (many firms)\n- Each offers unique menu, ambiance, location (differentiation)\n- Relatively easy to open new restaurant (low barriers)\n- Each has some pricing power but limited by competitors\n- Heavy use of advertising, reviews, branding\n- Example: Fast food chains, local eateries\n\nClothing retail:\n- Numerous brands and stores\n- Similar products but different styles, brands, quality\n- Fashion trends drive differentiation\n- E-commerce lowers entry barriers\n- Strong emphasis on branding and marketing\n- Example: H&M, Zara, Uniqlo compete but differentiated\n\nCoffee shops:\n- Many cafes in urban areas\n- Differentiated by location, quality, atmosphere\n- Easy entry for new cafes\n- Price differences exist but limited\n- Branding crucial (e.g., specialty vs. chain)\n- Example: Starbucks vs. local independent cafes\n\nBeauty salons/hairdressers:\n- Many providers\n- Differentiated by skill, reputation, service\n- Low barriers to entry\n- Some pricing power but competitive\n- Word-of-mouth and online reviews important',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Oligopoly (12 cards)
        {
            question: 'What are the key characteristics of oligopoly market structure?',
            answer: '1. Few dominant firms - market concentrated among small number of large firms (high concentration ratio)\n2. High barriers to entry - economies of scale, capital requirements, brand loyalty prevent entry\n3. Interdependence - each firm\'s decisions affect rivals (strategic behavior essential)\n4. Product differentiation or homogeneity - can be either (e.g., differentiated cars vs. homogeneous steel)\n5. Non-price competition important - advertising, innovation, quality\n\nKey feature: Mutual interdependence\n- Firms must consider rivals\' reactions to decisions\n- Strategic behavior and game theory relevant\n- Uncertainty about rivals\' responses\n\nExamples: Automobiles, airlines, telecommunications, soft drinks, supermarkets',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the concept of mutual interdependence in oligopoly markets.',
            answer: 'Mutual interdependence:\n\nDefinition:\n- Each firm\'s profit depends not only on its own actions but also on rivals\' responses\n- Must anticipate competitors\' reactions when making decisions\n\nImplications:\n\n1. Price decisions:\n   - Cannot ignore rivals when changing prices\n   - Price cut may trigger price war\n   - Price increase may lose market share if rivals don\'t follow\n\n2. Output decisions:\n   - Increasing output affects market price\n   - Rivals may respond by adjusting their output\n\n3. Strategic behavior:\n   - Game theory applies\n   - Must consider multiple scenarios\n   - Uncertainty about rivals\' actions\n\n4. Collusion incentive:\n   - Firms may cooperate to avoid destructive competition\n   - Maximize joint profits\n   - But unstable due to cheating incentive\n\nContrast with perfect competition (no interdependence) and monopoly (no rivals).',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the kinked demand curve model of oligopoly pricing.',
            answer: 'Kinked demand curve model:\n\nAssumptions:\n1. If firm raises price, rivals don\'t follow (lose customers)\n2. If firm cuts price, rivals match (no gain in market share)\n3. Creates kink in demand curve at current price P*\n\nDemand curve characteristics:\n- Above P*: Elastic (rivals don\'t follow price increase)\n- Below P*: Inelastic (rivals match price decrease)\n- Kink creates discontinuity in MR curve\n\nImplications:\n1. Price rigidity:\n   - Wide range of costs where P* remains optimal\n   - Changes in MC may not change price\n   - Explains stable prices despite cost variations\n\n2. Non-price competition:\n   - Price wars unprofitable\n   - Firms compete through advertising, quality, innovation\n\n3. Criticism:\n   - Doesn\'t explain how P* determined initially\n   - Oversimplified assumptions about rivals\' behavior\n   - Empirical evidence mixed',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What is collusion and why do oligopolists have incentive to collude?',
            answer: 'Collusion:\n\nDefinition: Agreement among firms to coordinate behavior, typically to restrict output and raise prices\n\nTypes:\n1. Explicit collusion (cartel):\n   - Formal agreement\n   - Coordinate prices, output, market shares\n   - Example: OPEC\n\n2. Tacit collusion:\n   - Informal coordination\n   - No explicit agreement\n   - Price leadership, signaling\n\nIncentive to collude:\n1. Avoid price wars - destructive competition reduces all firms\' profits\n2. Maximize joint profits - act as collective monopoly\n3. Reduce uncertainty - coordinate rather than guess rivals\' actions\n4. Share markets - agree on territories or customers\n\nBenefits:\n- Higher prices and profits\n- Stable market conditions\n- Reduced risk\n\nDrawbacks:\n- Illegal in most countries (antitrust laws)\n- Unstable (cheating incentive)\n- Difficult to coordinate\n- Entry threat',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain cartel theory and why cartels are inherently unstable.',
            answer: 'Cartel theory:\n\nCartel formation:\n1. Firms agree to restrict output below competitive level\n2. Raise price toward monopoly price\n3. Allocate production quotas among members\n4. Share monopoly profits\n\nWhy cartels are unstable:\n\n1. Cheating incentive:\n   - Each firm benefits from others restricting output\n   - Individual firm can increase profit by secretly exceeding quota\n   - At cartel price P*, MR > MC for each firm\n   - Prisoner\'s dilemma situation\n\n2. Detection difficulties:\n   - Hard to monitor compliance\n   - Secret price cuts, quality improvements\n   - Delayed discovery of cheating\n\n3. Entry threat:\n   - High prices attract new entrants\n   - If barriers weak, cartel profits eroded\n\n4. Coordination problems:\n   - Disagreements over quota allocation\n   - Different cost structures\n   - Conflicting interests\n\n5. Legal restrictions:\n   - Cartels illegal in most jurisdictions\n   - Risk of prosecution deters formation\n\nSuccessful cartels rare and temporary.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain tacit collusion and how it differs from explicit collusion.',
            answer: 'Tacit collusion:\n\nDefinition: Informal coordination without explicit agreement\n\nMechanisms:\n\n1. Price leadership:\n   - Dominant firm sets price\n   - Smaller firms follow\n   - No formal agreement needed\n   - Example: Barometric price leadership\n\n2. Parallel behavior:\n   - Firms independently reach similar decisions\n   - Observe and match rivals\' actions\n   - Focal points (e.g., round numbers)\n\n3. Trade associations:\n   - Information sharing\n   - Industry norms and standards\n   - Indirect coordination\n\nDifferences from explicit collusion:\n\nExplicit (cartel):\n- Formal agreement\n- Direct communication\n- Specific quotas and prices\n- Clearly illegal\n- More stable but risky\n\nTacit:\n- No formal agreement\n- Inferred coordination\n- General patterns\n- Legal gray area\n- Less stable but safer\n\nAdvantages of tacit collusion:\n- Avoids legal liability\n- More flexible\n- Easier to implement\n\nDisadvantages:\n- Less certain\n- Misunderstandings possible\n- Weaker compliance',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What is limit pricing and how does it act as a barrier to entry?',
            answer: 'Limit pricing:\n\nDefinition: Incumbent firms set price below profit-maximizing level to deter entry\n\nStrategy:\n1. Identify potential entrant\'s cost structure\n2. Set price below entrant\'s AC but above own AC\n3. Entry becomes unprofitable for potential competitor\n4. Incumbent sacrifices short-run profit for long-run market position\n\nConditions for effectiveness:\n1. Incumbent has cost advantage (economies of scale, experience)\n2. Credible commitment to maintain low price post-entry\n3. Entry requires significant sunk costs\n4. Incumbent can sustain period of lower profits\n\nMechanism:\n- Price < P_monopoly but P > AC_incumbent\n- P < AC_entrant\n- Entrant expects losses if enters\n- Deters entry, preserving incumbent\'s market power\n\nTrade-off:\n- Lower short-run profits\n- Avoid competition and protect long-run profits\n- Maintain market power\n\nCriticism:\n- May not be credible (why not raise price after entry deterred?)\n- Entrant may enter anyway if expects incumbent to accommodate',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain predatory pricing and evaluate its effectiveness as a competitive strategy.',
            answer: 'Predatory pricing:\n\nDefinition: Setting price below cost to drive competitors out of market, then raising price once rivals exit\n\nStrategy:\n1. Phase 1: Price below AC (or even AVC)\n2. Incumbent incurs losses but has deeper pockets\n3. Rivals cannot sustain losses and exit\n4. Phase 2: Raise price to recoup losses once competition eliminated\n\nRequirements:\n1. Financial strength to sustain losses\n2. Rivals are financially weaker\n3. Barriers prevent re-entry after price increase\n4. Can recoup losses with higher future profits\n\nProblems with strategy:\n\n1. Costly:\n   - Incumbent suffers losses during predatory phase\n   - May not recover losses if competition returns\n\n2. Difficult to sustain:\n   - How long can maintain below-cost prices?\n   - Rivals may survive longer than expected\n\n3. Entry threat:\n   - After raising price, new entrants may enter\n   - Hit-and-run entry possible\n   - Must repeat predation\n\n4. Legal issues:\n   - Illegal under competition law in many countries\n   - Antitrust prosecution risk\n\n5. Reputation effects:\n   - May deter future entry (benefit)\n   - But creates hostile regulatory environment\n\nEffectiveness debated: Rarely successful in practice.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the basic concepts of game theory as applied to oligopoly, using the Prisoner\'s Dilemma.',
            answer: 'Game theory in oligopoly:\n\nKey concepts:\n1. Players - firms making strategic decisions\n2. Strategies - possible actions (price, output, advertising)\n3. Payoffs - profits resulting from strategy combinations\n4. Nash equilibrium - outcome where no firm can improve by changing strategy alone\n\nPrisoner\'s Dilemma applied to oligopoly:\n\nScenario: Two firms deciding whether to collude (cooperate) or compete\n\nPayoff matrix example:\n                Firm B: Collude    Firm B: Compete\nFirm A: Collude     $10m, $10m        $2m, $15m\nFirm A: Compete     $15m, $2m         $5m, $5m\n\nAnalysis:\n1. Joint profit maximized if both collude ($10m each)\n2. Dominant strategy: Compete (better regardless of rival\'s choice)\n3. Nash equilibrium: Both compete ($5m each)\n4. Suboptimal outcome: Could earn more by colluding\n\nImplications:\n1. Individual rationality leads to collective irrationality\n2. Explains instability of cartels\n3. Why explicit agreements needed (but illegal)\n4. Repeated games may allow cooperation\n\nApplications: Price wars, advertising races, capacity expansion',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Distinguish between dominant strategy and Nash equilibrium in game theory.',
            answer: 'Dominant strategy:\n\nDefinition: A strategy that yields highest payoff regardless of what rivals do\n\nCharacteristics:\n1. Best response to all possible rival strategies\n2. Player should always choose dominant strategy\n3. Simplifies decision-making (no need to predict rivals)\n4. Not all games have dominant strategies\n\nExample (Prisoner\'s Dilemma):\n- "Compete" is dominant strategy for both firms\n- Yields higher profit whether rival colludes or competes\n\nNash equilibrium:\n\nDefinition: Outcome where each player\'s strategy is best response to others\' strategies - no player can improve by unilaterally changing\n\nCharacteristics:\n1. Mutual best response\n2. Stable outcome (no incentive to deviate)\n3. Requires predicting rivals\' choices\n4. May not be unique or exist\n\nRelationship:\n1. If all players have dominant strategies, their combination is Nash equilibrium\n2. Nash equilibrium can exist without dominant strategies\n3. Dominant strategy Nash equilibrium is strongest solution concept\n\nExample without dominant strategy:\n- Coordination games (e.g., technology standards)\n- Multiple Nash equilibria possible\n- Players must coordinate to reach efficient outcome',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Compare and contrast the efficiency outcomes of oligopoly with other market structures.',
            answer: 'Allocative efficiency:\n- Perfect competition: P = MC ✓\n- Monopoly: P > MC ✗ (worst)\n- Oligopoly: P > MC ✗ (between competition and monopoly)\n- Depends on collusion level\n\nProductive efficiency:\n- Perfect competition: P = minimum AC ✓ (long run)\n- Monopoly: P ≠ minimum AC ✗\n- Oligopoly: May or may not produce at minimum AC\n- Often some excess capacity\n\nX-efficiency:\n- Perfect competition: High competitive pressure ✓\n- Monopoly: Low pressure, organizational slack ✗\n- Oligopoly: Moderate pressure from rivals\n- Less slack than monopoly, more than perfect competition\n\nDynamic efficiency:\n- Perfect competition: Low (no supernormal profits for R&D)\n- Monopoly: Potentially high (profits fund innovation) but weak incentive\n- Oligopoly: Often highest\n  * Supernormal profits available for R&D\n  * Strong competitive pressure drives innovation\n  * Examples: Tech industry, pharmaceuticals\n\nConclusion:\nOligopoly shows mixed efficiency:\n- Static inefficiency (allocative, productive)\n- Potential dynamic efficiency advantages\n- Outcome depends on degree of competition vs. collusion',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Provide real-world examples of oligopolies and explain how they exhibit key characteristics.',
            answer: 'Automobile industry:\n- Few dominant firms: Toyota, Volkswagen, GM, Ford\n- High barriers: Massive capital requirements, economies of scale, brand loyalty\n- Interdependence: Price and model decisions affect rivals\n- Product differentiation: Brand, features, quality\n- Non-price competition: Innovation, safety features, advertising\n\nTelecommunications:\n- Few major carriers in each country\n- High barriers: Infrastructure costs, spectrum licenses\n- Mutual interdependence: Pricing plans respond to rivals\n- Homogeneous service but differentiated packages\n- Heavy advertising and network quality competition\n\nAirlines:\n- Concentrated markets (especially routes)\n- Barriers: Landing slots, airport access, loyalty programs\n- Price interdependence: Fare matching common\n- Service differentiation: Premium vs. budget\n- Alliances and code-sharing (tacit collusion)\n\nSoft drinks:\n- Coca-Cola and PepsiCo dominate\n- Barriers: Brand loyalty, distribution networks, economies of scale\n- Strategic rivalry: Marketing battles, new product launches\n- Product differentiation: Flavors, branding\n- Extensive advertising and sponsorships\n\nSupermarkets:\n- Few large chains in most markets\n- Barriers: Scale economies, prime locations, supply chain\n- Price competition but loyalty programs\n- Some differentiation: Store brands, service levels\n- Location and convenience competition',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Non-price Competition (5 cards)
        {
            question: 'What is non-price competition and why is it important in imperfectly competitive markets?',
            answer: 'Non-price competition:\n\nDefinition: Competing through factors other than price - quality, features, service, branding, innovation\n\nWhy important in imperfect competition:\n\n1. Avoid price wars:\n   - Price cuts trigger retaliation\n   - Mutually destructive\n   - Difficult to sustain competitive advantage through price\n\n2. Product differentiation:\n   - Creates brand loyalty\n   - Makes demand less elastic\n   - Allows premium pricing\n\n3. Build barriers:\n   - Strong brands harder to challenge\n   - Customer lock-in\n   - Network effects\n\n4. Sustain profits:\n   - Non-price features harder to copy\n   - Quality and innovation provide lasting advantage\n   - Brand reputation takes time to build\n\nForms of non-price competition:\n1. Product innovation - new features, improved quality\n2. Process innovation - lower costs, better efficiency\n3. Marketing and advertising - brand building\n4. After-sales service - warranties, support\n5. Location and convenience\n6. Corporate social responsibility\n\nParticularly important in oligopoly and monopolistic competition.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain how mergers and acquisitions (M&A) can be used as a competitive strategy in oligopolistic markets.',
            answer: 'M&A as competitive strategy:\n\nTypes:\n1. Horizontal integration - merge with competitor\n2. Vertical integration - merge with supplier or distributor\n3. Conglomerate - merge with unrelated business\n\nMotives in oligopoly:\n\n1. Increase market power:\n   - Reduce competition\n   - Gain pricing power\n   - Increase concentration ratio\n\n2. Economies of scale:\n   - Spread fixed costs over larger output\n   - Bulk purchasing discounts\n   - Rationalize operations\n\n3. Reduce rivalry:\n   - Eliminate competitor\n   - Less uncertainty from interdependence\n   - Easier to coordinate (fewer firms)\n\n4. Access to resources:\n   - Technology, patents, expertise\n   - Distribution networks\n   - Customer base\n\n5. Diversification:\n   - Spread risk across markets\n   - Counter seasonal variations\n   - Enter new markets quickly\n\nRegulatory concerns:\n- Competition authorities scrutinize mergers\n- May block if reduces competition substantially\n- Efficiency gains must outweigh competitive harm\n\nExamples: Tech giants acquiring startups, airline mergers, pharmaceutical consolidation',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the role of diversification as a competitive strategy and its potential benefits and risks.',
            answer: 'Diversification strategy:\n\nDefinition: Expanding into new products or markets beyond core business\n\nTypes:\n1. Related diversification - similar products or markets\n2. Unrelated diversification - different industries\n\nBenefits:\n\n1. Risk reduction:\n   - Spread across multiple markets\n   - Reduce dependence on single product/market\n   - Counter cyclical variations\n\n2. Growth opportunities:\n   - Saturated core market\n   - Leverage existing capabilities\n   - Cross-selling opportunities\n\n3. Economies of scope:\n   - Share resources across products\n   - Common distribution, marketing, R&D\n   - Synergies between divisions\n\n4. Competitive advantage:\n   - Bundle products\n   - One-stop shopping for customers\n   - Cross-subsidization possible\n\nRisks:\n\n1. Loss of focus:\n   - Dilute core competencies\n   - Complexity of managing diverse businesses\n   - Resource allocation challenges\n\n2. Diseconomies of scale:\n   - Coordination costs\n   - Bureaucracy\n   - Reduced efficiency\n\n3. Unsuccessful ventures:\n   - Unfamiliar markets\n   - Lack of expertise\n   - Cultural integration problems\n\n4. Regulatory issues:\n   - Antitrust concerns\n   - Conglomerate discount in stock market\n\nExamples: Samsung (electronics to construction), GE (multiple industries)',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Distinguish between product innovation and process innovation as forms of non-price competition.',
            answer: 'Product innovation:\n\nDefinition: Developing new products or improving existing products\n\nExamples:\n- New features (smartphone capabilities)\n- Improved quality (better materials)\n- New models (product line extensions)\n- Entirely new products (tablets, smartwatches)\n\nObjectives:\n1. Differentiate from rivals\n2. Command premium prices\n3. Attract new customers\n4. Enter new markets\n5. Protect market share\n\nBenefits:\n- Consumer appeal\n- Brand enhancement\n- Market leadership\n- Higher margins\n\nRisks:\n- High R&D costs\n- Uncertain consumer acceptance\n- Quick imitation by rivals\n\nProcess innovation:\n\nDefinition: Improving production methods to reduce costs or improve efficiency\n\nExamples:\n- Automation (robotics)\n- Better logistics (just-in-time)\n- New production techniques\n- Digital transformation\n\nObjectives:\n1. Lower average costs\n2. Improve quality consistency\n3. Faster production\n4. Reduce waste\n5. Competitive cost advantage\n\nBenefits:\n- Higher profit margins\n- Competitive pricing possible\n- Scalability\n- Quality improvements\n\nRisks:\n- Implementation costs\n- Worker resistance\n- Technology obsolescence\n\nBoth important but product innovation more visible to consumers.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Evaluate the role of marketing and advertising as forms of non-price competition in oligopolistic markets.',
            answer: 'Role of marketing and advertising:\n\nPositive arguments:\n\n1. Information provision:\n   - Educate consumers about products\n   - Reduce search costs\n   - Compare features and prices\n   - Enable informed decisions\n\n2. Competition stimulus:\n   - Encourage product improvement\n   - Drive innovation\n   - Firms must deliver on promises\n   - Quality signals\n\n3. Economic benefits:\n   - Support employment (advertising industry)\n   - Fund media content (free TV, newspapers)\n   - Economies of scale from increased sales\n\n4. Consumer choice:\n   - Make consumers aware of alternatives\n   - Introduce new products\n   - Facilitate market entry\n\nNegative arguments:\n\n1. Persuasive rather than informative:\n   - Manipulate preferences\n   - Create artificial wants\n   - Psychological persuasion\n   - Emotional rather than rational appeals\n\n2. Increases costs:\n   - Raises AC for all firms\n   - Passed to consumers as higher prices\n   - Wasteful expenditure\n   - Resources could be better used\n\n3. Barriers to entry:\n   - Established brands hard to challenge\n   - New entrants need huge marketing budgets\n   - Reduces competition\n   - Entrenches incumbents\n\n4. Advertising wars:\n   - Escalating expenditure\n   - Prisoner\'s dilemma\n   - Offsetting effects\n   - No net gain in market share\n\nConclusion: Benefits depend on whether advertising is informative or purely persuasive.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Microeconomics',
            chapter: 'Market Structure',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(flashcards).values(sampleFlashcards);
    
    console.log('✅ Market Structure flashcards seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});