import { db } from '@/db';
import { flashcards } from '@/db/schema';

async function main() {
    const currentTimestamp = new Date().toISOString();
    
    const sampleFlashcards = [
        {
            question: "What is the definition of Short Run in economics?",
            answer: "Short Run is defined as a period over which at least one factor input is fixed.",
            level: "JC",
            category: "Theory",
            topic: "Definitions",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the definition of Long Run in economics?",
            answer: "Long Run is defined as a period over which all factors used in the production process are variable.",
            level: "JC",
            category: "Theory",
            topic: "Definitions",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "Define Economies of Scale.",
            answer: "Economies of Scale refers to cost savings enjoyed from large-scale production.",
            level: "JC",
            category: "Theory",
            topic: "Definitions",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What are Barriers to Entry?",
            answer: "Barriers to entry refers to anything that prevents or impedes the entry of new firms into an industry and thereby limits the degree of competition faced by existing firms.",
            level: "JC",
            category: "Theory",
            topic: "Definitions",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "Define Allocative Efficiency.",
            answer: "Allocative efficiency refers to the current combination of goods produced and sold that gives the maximum satisfaction for each consumer at the current level of income. This occurs when P=MC.",
            level: "JC",
            category: "Theory",
            topic: "Definitions",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Productive Efficiency?",
            answer: "Productive efficiency refers to the situation when output is produced with the least costly combinations of inputs given the current level of technology.",
            level: "JC",
            category: "Theory",
            topic: "Definitions",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "Define Dynamic Efficiency.",
            answer: "Dynamic efficiency refers to the situation where firms are technologically progressive through investing in R&D to meet the changing needs and wants of consumers over time.",
            level: "JC",
            category: "Theory",
            topic: "Definitions",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Equity in economic terms?",
            answer: "Equity is defined as a distribution of income that is considered to be fair or just.",
            level: "JC",
            category: "Theory",
            topic: "Definitions",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Internal Economies of Scale (IEOS) and what happens to average cost?",
            answer: "Internal Economies of Scale occurs when an increase in output leads to a less than proportionate increase in total cost, resulting in average cost decreasing. This is shown as a movement along the firm's LRAC curve.",
            level: "JC",
            category: "Cost Theory",
            topic: "Economies of Scale",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What are the sources of Internal Economies of Scale?",
            answer: "Sources of IEOS include: specialization & division of labour, indivisibilities of machinery, bulk purchases, and large scale advertising.",
            level: "JC",
            category: "Cost Theory",
            topic: "Economies of Scale",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Internal Diseconomies of Scale (IDOS)?",
            answer: "Internal Diseconomies of Scale occurs when an increase in output leads to a more than proportionate increase in total cost, resulting in average cost increasing.",
            level: "JC",
            category: "Cost Theory",
            topic: "Economies of Scale",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What are the sources of Internal Diseconomies of Scale?",
            answer: "Sources of IDOS include: managerial difficulties and low morale.",
            level: "JC",
            category: "Cost Theory",
            topic: "Economies of Scale",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is External Economies of Scale and how does it affect LRAC?",
            answer: "External Economies of Scale is a reduction in unit costs from expansion or growth of the industry, leading to a downward shift in the firm's LRAC curve.",
            level: "JC",
            category: "Cost Theory",
            topic: "Economies of Scale",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What are the sources of External Economies of Scale?",
            answer: "Sources include: better infrastructure within an area of concentrated operations, and joint efforts in R&D by firms within the same industry.",
            level: "JC",
            category: "Cost Theory",
            topic: "Economies of Scale",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is External Diseconomies of Scale?",
            answer: "External Diseconomies of Scale is an increase in unit cost from expansion or growth of industry, leading to an upward shift in LRAC.",
            level: "JC",
            category: "Cost Theory",
            topic: "Economies of Scale",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What are the three types of Barriers to Entry?",
            answer: "The three types are: Structural BTEs (related to basic industry conditions), Strategic BTEs (created intentionally by incumbent firms), and Statutory BTEs (created by government through laws and regulations).",
            level: "JC",
            category: "Market Structure",
            topic: "Barriers to Entry",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "Give examples of Structural Barriers to Entry.",
            answer: "Examples include: High capital outlay (very costly technology required) and Internal economies of scale (MES occurs at high levels of output, making it difficult for new smaller firms to compete).",
            level: "JC",
            category: "Market Structure",
            topic: "Barriers to Entry",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What are examples of Strategic Barriers to Entry?",
            answer: "Examples include: Aggressive pricing strategies (price wars, predatory pricing, limit pricing), Product recognition (marketing to create brand loyalty), and Control of essential FOP through exclusive deals with suppliers.",
            level: "JC",
            category: "Market Structure",
            topic: "Barriers to Entry",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What are examples of Statutory Barriers to Entry?",
            answer: "Examples include: Licenses (government issues limited number of licenses) and Intellectual property rights (patents, copyrights, franchises that prevent imitation).",
            level: "JC",
            category: "Market Structure",
            topic: "Barriers to Entry",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the profit-maximizing condition for a firm?",
            answer: "A firm profit-maximizes where MC=MR and MC cuts MR from below.",
            level: "JC",
            category: "Firm Behaviour",
            topic: "Firm Objectives",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "Explain why a firm should produce where MR>MC.",
            answer: "When MR>MC, marginal profit is positive for every additional unit produced. Additional revenue generated is greater than the additional cost, so a profit-maximizing firm should continue to expand production to increase profits.",
            level: "JC",
            category: "Firm Behaviour",
            topic: "Firm Objectives",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What happens when a firm produces where MR<MC?",
            answer: "When MR<MC, marginal profit is negative. Additional revenue generated is less than the additional cost of producing each extra unit, so the firm should cut back on production to increase profits.",
            level: "JC",
            category: "Firm Behaviour",
            topic: "Firm Objectives",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the sales revenue maximizing condition?",
            answer: "A sales revenue maximizing firm produces where MR=0.",
            level: "JC",
            category: "Firm Behaviour",
            topic: "Firm Objectives",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "Why does a firm maximize revenue at MR=0?",
            answer: "At MR=0, increasing output no longer adds to the total revenue of the firm. Revenue is at its maximum at this point because any further increase in output would result in negative MR, reducing total revenue.",
            level: "JC",
            category: "Firm Behaviour",
            topic: "Firm Objectives",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the short run shutdown condition for a firm?",
            answer: "In the short run, a firm should shut down if AVC>AR or TVC>TR (total revenue is unable to cover total variable costs).",
            level: "JC",
            category: "Firm Behaviour",
            topic: "Firm Objectives",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "Why should a firm shut down in the short run if TVC>TR?",
            answer: "Fixed costs cannot be avoided even if the firm shuts down. If TVC>TR, continuing production means incurring TVC that cannot be fully covered. Shutting down means only incurring TFC, which minimizes losses.",
            level: "JC",
            category: "Firm Behaviour",
            topic: "Firm Objectives",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the long run shutdown condition?",
            answer: "In the long run, a firm should shut down if AC>AR or TC>TR. The firm must make at least normal profits to stay in the industry.",
            level: "JC",
            category: "Firm Behaviour",
            topic: "Firm Objectives",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What are reasons why firms may not always be profit-maximizing?",
            answer: "Reasons include: Profit-satisficing behaviour (principal agent problem), Non-economic motives (ESG concerns), Imperfect information (firms don't know their own MC and MR), and Short term goals (sales revenue or growth maximizing).",
            level: "JC",
            category: "Firm Behaviour",
            topic: "Firm Objectives",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Predatory Pricing and what is its goal?",
            answer: "Predatory pricing is a strategic barrier to entry where an incumbent firm lowers its price below its average costs to drive out competitors already in the market. Competitors without financial reserves will be forced to exit.",
            level: "JC",
            category: "Firm Strategy",
            topic: "Pricing Strategies",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Limit Pricing and what is its goal?",
            answer: "Limit pricing is a strategy to deter potential entrants by making entry unattractive. The firm lowers price to where AR=AC, making only normal profit, so entering the market becomes unattractive to potential entrants.",
            level: "JC",
            category: "Firm Strategy",
            topic: "Pricing Strategies",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the short run impact of predatory pricing on consumers?",
            answer: "In the short run: lower prices, larger output, and consumer surplus increases.",
            level: "JC",
            category: "Firm Strategy",
            topic: "Pricing Strategies",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the long run impact of predatory pricing on consumers?",
            answer: "In the long run: once competitors are driven out, the firm gains market power, can set higher prices, offers lower output, provides lower variety, and potentially poorer quality of service.",
            level: "JC",
            category: "Firm Strategy",
            topic: "Pricing Strategies",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the goal of collusion or cartel formation?",
            answer: "The goal is for firms within a market to collude and act as one entity or a monopoly to charge the monopoly price and increase total profits.",
            level: "JC",
            category: "Firm Strategy",
            topic: "Pricing Strategies",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Price Discrimination?",
            answer: "Price discrimination is a strategy to increase revenue or profits by increasing price for a relatively price inelastic segment of the market and decreasing price for the relatively price elastic segment.",
            level: "JC",
            category: "Firm Strategy",
            topic: "Pricing Strategies",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the impact of collusion on allocative efficiency?",
            answer: "Collusion leads to greater allocative inefficiency as the price markup (gap between P and MC) increases.",
            level: "JC",
            category: "Firm Strategy",
            topic: "Pricing Strategies",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "How does collusion affect dynamic efficiency?",
            answer: "The effect on dynamic efficiency is ambiguous. Ability to conduct R&D increases due to increased profits, but willingness to conduct R&D decreases due to decreased competition.",
            level: "JC",
            category: "Firm Strategy",
            topic: "Pricing Strategies",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Product Differentiation and what is its goal?",
            answer: "Product differentiation is a strategy to distinguish a firm's product from competing firms, reducing PED and substitutability, and increasing demand. This can lead to increased prices and profits.",
            level: "JC",
            category: "Firm Strategy",
            topic: "Non-Price Strategies",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the goal of Mergers and Acquisitions?",
            answer: "The goal is to gain access to new markets and ideas, or secure essential factors of production. This typically leads to increased demand, more price inelastic demand due to reduced competitors, and increased profits.",
            level: "JC",
            category: "Firm Strategy",
            topic: "Non-Price Strategies",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Firms & Decisions",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "Define Demand.",
            answer: "Demand is defined as the quantity of a good (or service) that a consumer is both willing and able to buy at each possible price during a given period of time, ceteris paribus.",
            level: "JC",
            category: "Market Theory",
            topic: "Demand and Supply",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "Define Supply.",
            answer: "Supply is defined as the quantity of a good or service that a producer is both willing and able to sell at each possible price during a given period of time, ceteris paribus.",
            level: "JC",
            category: "Market Theory",
            topic: "Demand and Supply",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Price Elasticity of Demand (PED)?",
            answer: "Price elasticity of demand is a measure of the degree of responsiveness of the quantity demanded for a good to a change in the price of the good itself, ceteris paribus.",
            level: "JC",
            category: "Market Theory",
            topic: "Elasticity",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Price Elasticity of Supply (PES)?",
            answer: "Price elasticity of supply is a measure of the responsiveness of the quantity supplied of a good to changes in its price, ceteris paribus.",
            level: "JC",
            category: "Market Theory",
            topic: "Elasticity",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Income Elasticity of Demand (YED)?",
            answer: "Income elasticity of demand is a measure of the degree of responsiveness of the demand for a good to a change in income, ceteris paribus.",
            level: "JC",
            category: "Market Theory",
            topic: "Elasticity",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is Cross Elasticity of Demand (XED)?",
            answer: "Cross elasticity of demand is a measure of the degree of responsiveness of the demand for one good to a change in the price of another good, ceteris paribus.",
            level: "JC",
            category: "Market Theory",
            topic: "Elasticity",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What are the non-price factors that cause a shift in demand? (Use EGYPT mnemonic)",
            answer: "E - Expectations of future price change, G - Government policies, Y - Income, P - Price of related goods (substitutes/complements) and Population size, T - Tastes and Preferences.",
            level: "JC",
            category: "Market Theory",
            topic: "Demand and Supply",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What causes a shift in the supply curve?",
            answer: "Non-price factors including: Number of sellers, Marginal cost of production, Unpredicted Events/Supply shocks, Quantity of goods in joint supply or competitive supply, Expectations of future price change, and Government policies.",
            level: "JC",
            category: "Market Theory",
            topic: "Demand and Supply",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the difference between demand and quantity demanded?",
            answer: "Demand refers to the entire demand curve, while quantity demanded refers to a point on the demand curve. A change in non-price factors shifts the demand curve, while a change in price causes a movement along the curve.",
            level: "JC",
            category: "Market Theory",
            topic: "Demand and Supply",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What happens when there is an increase in demand?",
            answer: "When demand increases (shifts right), quantity demanded has increased at all prices. This creates a shortage at the original price, causing upward pressure on price until a new equilibrium is reached.",
            level: "JC",
            category: "Market Theory",
            topic: "Demand and Supply",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What are the factors affecting PED? (Use SPLAT mnemonic)",
            answer: "S - Substitutability (availability of close substitutes), P - Proportion of income spent on the good, L - Luxury or necessity, A - Addiction, T - Time.",
            level: "JC",
            category: "Market Theory",
            topic: "Elasticity",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What are the factors affecting PES? (Use MEAT mnemonic)",
            answer: "M - Mobility of FOPs, E - Existence of spare capacity, A - Availability of stocks, T - Time.",
            level: "JC",
            category: "Market Theory",
            topic: "Elasticity",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What does it mean when YED is positive vs negative?",
            answer: "YED>0 indicates a normal good (demand increases when income increases), while YED<0 indicates an inferior good (demand decreases when income increases).",
            level: "JC",
            category: "Market Theory",
            topic: "Elasticity",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What is the difference between necessity and luxury goods in terms of YED?",
            answer: "For normal goods: a necessity has 0<YED<1 (demand increases less than proportionally with income), while a luxury has YED>1 (demand increases more than proportionally with income).",
            level: "JC",
            category: "Market Theory",
            topic: "Elasticity",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What does the sign of XED tell us about the relationship between goods?",
            answer: "XED>0 indicates substitutes (demand for good B increases when price of good A increases), while XED<0 indicates complements (demand for good B decreases when price of good A increases).",
            level: "JC",
            category: "Market Theory",
            topic: "Elasticity",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "How do we determine the closeness of relationship using XED?",
            answer: "A weak relationship has 0<XED<1, while a strong relationship has XED>1. The larger the magnitude, the closer the relationship between the goods.",
            level: "JC",
            category: "Market Theory",
            topic: "Elasticity",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What happens when there is a shortage in the market?",
            answer: "At a price below equilibrium, quantity demanded exceeds quantity supplied, creating a shortage. Buyers competing for the good bid up prices. As price rises, quantity demanded decreases and quantity supplied increases until equilibrium is restored.",
            level: "JC",
            category: "Market Theory",
            topic: "Market Analysis",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "What happens when there is a surplus in the market?",
            answer: "At a price above equilibrium, quantity supplied exceeds quantity demanded, creating a surplus. Firms cut prices to remove the surplus. As price falls, quantity demanded rises and quantity supplied falls until equilibrium is restored.",
            level: "JC",
            category: "Market Theory",
            topic: "Market Analysis",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "In a double shift analysis with increase in demand and increase in supply, which variable is always indeterminate?",
            answer: "Price is indeterminate. Both shifts lead to an increase in quantity, but increase in demand leads to higher price while increase in supply leads to lower price, so the overall price change depends on the relative extent of the shifts.",
            level: "JC",
            category: "Market Theory",
            topic: "Market Analysis",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "How do you analyze the impact of an increase in supply on revenue?",
            answer: "An increase in supply leads to lower price and higher quantity. Since revenue = P×Q, revenue is indeterminate. If PED<1 (inelastic), the decrease in revenue from lower price is larger than the increase from higher quantity, so revenue decreases overall.",
            level: "JC",
            category: "Market Theory",
            topic: "Market Analysis",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "Why is PES not required to analyze revenue changes from an increase in demand?",
            answer: "When demand increases, both price and quantity increase, which both contribute to higher total revenue (P×Q). Regardless of the PES value, total revenue will always increase.",
            level: "JC",
            category: "Market Theory",
            topic: "Market Analysis",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: "How do you use PED to evaluate the extent of price and quantity changes from a decrease in supply?",
            answer: "If PED<1 (inelastic demand), a decrease in supply leads to a large increase in price but only a small decrease in quantity, because the higher price leads to a less than proportionate decrease in quantity demanded.",
            level: "JC",
            category: "Market Theory",
            topic: "Market Analysis",
            difficulty: null,
            economicsType: "Microeconomics",
            chapter: "Price Mechanism",
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    await db.insert(flashcards).values(sampleFlashcards);
    
    console.log('✅ Flashcards seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});