import { db } from '@/db';
import { flashcards } from '@/db/schema';

async function main() {
    const currentTimestamp = new Date().toISOString();
    
    const sampleFlashcards = [
        {
            question: 'Define equilibrium price and equilibrium quantity in a market.',
            answer: 'Equilibrium price is the price at which quantity demanded equals quantity supplied in a market. At this price, there is no tendency for price to change as the market clears with no surplus or shortage.\n\nEquilibrium quantity is the quantity bought and sold at the equilibrium price, where quantity demanded equals quantity supplied.\n\nFor example, if the demand and supply for HDB flats in Singapore intersect at a price of $400,000 and quantity of 10,000 units, then $400,000 is the equilibrium price and 10,000 units is the equilibrium quantity. At this point, all buyers willing to pay $400,000 can find sellers, and all sellers willing to sell at $400,000 can find buyers.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'easy',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain how the market reaches equilibrium through the price mechanism when there is a surplus.',
            answer: 'When market price is above equilibrium (e.g., P1 > Pe), quantity supplied exceeds quantity demanded, creating a surplus.\n\nSurplus elimination process:\n1. Surplus accumulates as unsold goods pile up (e.g., unsold chicken rice at hawker centers at closing time)\n2. Sellers compete to clear inventory by lowering prices\n3. As price falls, quantity demanded rises (moving down along the demand curve) and quantity supplied falls (moving down along the supply curve)\n4. This process continues until price reaches Pe where Qd = Qs\n5. The surplus is eliminated and market clears\n\nDiagram: Draw demand and supply curves intersecting at equilibrium point E. Mark a price P1 above Pe. At P1, show Qs1 > Qd1, with the horizontal distance representing the surplus. Draw downward arrows showing price falling from P1 to Pe, with the surplus shrinking to zero at equilibrium.\n\nExample: During Singapore\'s Circuit Breaker in 2020, many F&B outlets had excess prepared food. Prices were slashed through promotions to clear the surplus.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'medium',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Explain how the market reaches equilibrium through the price mechanism when there is a shortage.',
            answer: 'When market price is below equilibrium (e.g., P2 < Pe), quantity demanded exceeds quantity supplied, creating a shortage.\n\nShortage elimination process:\n1. Shortage occurs as consumers compete for limited goods (e.g., long queues for subsidized masks during COVID-19)\n2. Buyers bid up prices or sellers raise prices to ration scarce goods\n3. As price rises, quantity demanded falls (moving up along the demand curve) and quantity supplied rises (moving up along the supply curve)\n4. This process continues until price reaches Pe where Qd = Qs\n5. The shortage is eliminated and market clears\n\nDiagram: Draw demand and supply curves intersecting at equilibrium point E. Mark a price P2 below Pe. At P2, show Qd2 > Qs2, with the horizontal distance representing the shortage. Draw upward arrows showing price rising from P2 to Pe, with the shortage shrinking to zero at equilibrium.\n\nExample: When Nintendo Switch was first launched in Singapore, high demand at the initial price created shortages. Retailers gradually raised prices until the market cleared at a higher equilibrium price.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'medium',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Define surplus, explain its causes, and describe the elimination mechanism with diagram.',
            answer: 'Surplus Definition: A market surplus occurs when quantity supplied exceeds quantity demanded at a given price. It represents excess supply where sellers cannot sell all they wish to sell at the current price.\n\nCauses of Surplus:\n1. Price set above equilibrium (e.g., government price floor)\n2. Demand decreases while price remains constant\n3. Supply increases while price remains constant\n\nElimination Mechanism:\n- Unsold inventory accumulates, increasing storage costs\n- Sellers compete by offering discounts and promotions\n- Price falls, causing Qd to rise and Qs to fall\n- Process continues until surplus is eliminated at equilibrium\n\nDiagram Description:\nVertical axis: Price (P), Horizontal axis: Quantity (Q)\n- Draw downward-sloping demand curve (D) and upward-sloping supply curve (S)\n- Mark equilibrium at point E where D and S intersect (Pe, Qe)\n- Draw horizontal line at P1 > Pe\n- At P1: Qs1 on supply curve, Qd1 on demand curve\n- Show surplus as horizontal distance between Qs1 and Qd1\n- Draw downward arrows from P1 toward Pe showing price adjustment\n- Label "Surplus eliminated through falling price"\n\nExample: Singapore\'s retail property market in 2023 saw surplus office space in the CBD as many companies adopted hybrid work, leading to falling rental prices.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'medium',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Define shortage, explain its causes, and describe the elimination mechanism with diagram.',
            answer: 'Shortage Definition: A market shortage occurs when quantity demanded exceeds quantity supplied at a given price. It represents excess demand where buyers cannot purchase all they wish to buy at the current price.\n\nCauses of Shortage:\n1. Price set below equilibrium (e.g., government price ceiling)\n2. Demand increases while price remains constant\n3. Supply decreases while price remains constant\n\nElimination Mechanism:\n- Long queues form and stockouts occur\n- Buyers compete by offering higher prices\n- Sellers raise prices to ration scarce goods\n- Price rises, causing Qd to fall and Qs to rise\n- Process continues until shortage is eliminated at equilibrium\n\nDiagram Description:\nVertical axis: Price (P), Horizontal axis: Quantity (Q)\n- Draw downward-sloping demand curve (D) and upward-sloping supply curve (S)\n- Mark equilibrium at point E where D and S intersect (Pe, Qe)\n- Draw horizontal line at P2 < Pe\n- At P2: Qd2 on demand curve, Qs2 on supply curve\n- Show shortage as horizontal distance between Qs2 and Qd2\n- Draw upward arrows from P2 toward Pe showing price adjustment\n- Label "Shortage eliminated through rising price"\n\nExample: During Singapore\'s 2013 "haze crisis," N95 masks faced severe shortage at original retail prices. Prices surged as consumers competed for limited supply, eventually reaching a new equilibrium at higher prices.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'medium',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Analyze a rightward shift in demand: What happens to equilibrium price and quantity? Provide examples.',
            answer: 'When demand increases (rightward shift from D0 to D1), with supply unchanged:\n\nNew Equilibrium Analysis:\n- Initial equilibrium: E0 (P0, Q0)\n- Demand shifts right to D1\n- At original price P0, Qd > Qs, creating shortage\n- Shortage causes price to rise\n- New equilibrium: E1 (P1, Q1)\n- Result: Both P and Q increase (P1 > P0, Q1 > Q0)\n\nMechanism:\n1. Initial shortage at P0\n2. Consumers bid up prices\n3. Higher prices induce greater quantity supplied (movement along S)\n4. Higher prices reduce quantity demanded (movement along D1)\n5. Market clears at higher P1 and Q1\n\nDiagram: Draw original D0 and S intersecting at E0. Shift demand right to D1. New intersection at E1 shows higher price P1 and higher quantity Q1. Draw dotted lines to show the increase in both P and Q.\n\nExamples:\n1. Electric vehicles in Singapore: Government incentives increased demand, leading to higher prices and more EVs sold\n2. Bubble tea market: Rising popularity among youth shifted demand right, causing both prices and quantity of bubble tea outlets to increase\n3. Private tuition: Increased emphasis on education during COVID-19 shifted demand right, raising tuition fees and number of tutors hired\n4. HDB resale flats (2021-2022): Strong demand from upgraders led to higher resale prices and transaction volume',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'medium',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Analyze a leftward shift in demand: What happens to equilibrium price and quantity? Provide examples.',
            answer: 'When demand decreases (leftward shift from D0 to D2), with supply unchanged:\n\nNew Equilibrium Analysis:\n- Initial equilibrium: E0 (P0, Q0)\n- Demand shifts left to D2\n- At original price P0, Qs > Qd, creating surplus\n- Surplus causes price to fall\n- New equilibrium: E2 (P2, Q2)\n- Result: Both P and Q decrease (P2 < P0, Q2 < Q0)\n\nMechanism:\n1. Initial surplus at P0\n2. Sellers lower prices to clear inventory\n3. Lower prices reduce quantity supplied (movement along S)\n4. Lower prices increase quantity demanded (movement along D2)\n5. Market clears at lower P2 and Q2\n\nDiagram: Draw original D0 and S intersecting at E0. Shift demand left to D2. New intersection at E2 shows lower price P2 and lower quantity Q2. Draw dotted lines to show the decrease in both P and Q.\n\nExamples:\n1. Petrol-powered cars in Singapore: Rising environmental awareness and EV incentives decreased demand for petrol cars, lowering both prices and sales volume\n2. Office space in CBD (post-COVID): Hybrid work arrangements reduced demand for office space, causing rental prices and occupancy rates to fall\n3. Formal dining restaurants (2020): Circuit Breaker restrictions and changed preferences shifted demand left, reducing both prices (through promotions) and covers served\n4. Desktop computers: Rise of laptops and tablets decreased demand for desktops, leading to lower prices and fewer units sold',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'medium',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Analyze a rightward shift in supply: What happens to equilibrium price and quantity? Provide examples.',
            answer: 'When supply increases (rightward shift from S0 to S1), with demand unchanged:\n\nNew Equilibrium Analysis:\n- Initial equilibrium: E0 (P0, Q0)\n- Supply shifts right to S1\n- At original price P0, Qs > Qd, creating surplus\n- Surplus causes price to fall\n- New equilibrium: E1 (P1, Q1)\n- Result: P decreases, Q increases (P1 < P0, Q1 > Q0)\n\nMechanism:\n1. Initial surplus at P0\n2. Competing sellers lower prices\n3. Lower prices increase quantity demanded (movement along D)\n4. Lower prices reduce quantity supplied (movement along S1)\n5. Market clears at lower P1 but higher Q1\n\nDiagram: Draw original D and S0 intersecting at E0. Shift supply right to S1. New intersection at E1 shows lower price P1 and higher quantity Q1. Draw dotted lines showing P falling and Q rising.\n\nExamples:\n1. Solar panels in Singapore: Technological improvements increased supply, reducing prices while more households installed solar panels\n2. Grab/Gojek rides: Entry of new drivers increased supply, leading to lower fares and more rides completed\n3. Smartphone market: Improved manufacturing efficiency increased supply, causing prices to fall while more units were sold\n4. Local produce (vertical farms): New vertical farming technology in Singapore increased supply of vegetables, lowering prices and increasing consumption',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'medium',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Analyze a leftward shift in supply: What happens to equilibrium price and quantity? Provide examples.',
            answer: 'When supply decreases (leftward shift from S0 to S2), with demand unchanged:\n\nNew Equilibrium Analysis:\n- Initial equilibrium: E0 (P0, Q0)\n- Supply shifts left to S2\n- At original price P0, Qd > Qs, creating shortage\n- Shortage causes price to rise\n- New equilibrium: E2 (P2, Q2)\n- Result: P increases, Q decreases (P2 > P0, Q2 < Q0)\n\nMechanism:\n1. Initial shortage at P0\n2. Consumers bid up prices for scarce goods\n3. Higher prices reduce quantity demanded (movement along D)\n4. Higher prices increase quantity supplied (movement along S2)\n5. Market clears at higher P2 but lower Q2\n\nDiagram: Draw original D and S0 intersecting at E0. Shift supply left to S2. New intersection at E2 shows higher price P2 and lower quantity Q2. Draw dotted lines showing P rising and Q falling.\n\nExamples:\n1. Construction materials (2021-2022): Supply chain disruptions and Ukraine war reduced supply, raising prices of steel and cement while construction projects slowed\n2. Hawker food: Manpower shortages and rising costs caused some hawker stalls to close, reducing supply and raising prices while fewer meals were served\n3. Fresh vegetables (Malaysian import restrictions): When Malaysia restricted exports, supply of vegetables in Singapore fell, causing prices to spike while less was consumed\n4. COE premiums: Government\'s reduced COE quota decreased supply of car ownership rights, causing COE prices to soar while fewer cars were registered',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'medium',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Analyze double shift: Both demand and supply increase. What is certain and what is indeterminate about the new equilibrium?',
            answer: 'When both demand and supply increase (D shifts right, S shifts right):\n\nAnalysis:\n- Demand increase alone: P↑, Q↑\n- Supply increase alone: P↓, Q↑\n- Combined effect:\n  * Price (P): INDETERMINATE - depends on relative magnitude of shifts\n  * Quantity (Q): CERTAIN to increase - both shifts increase Q\n\nThree Scenarios:\n1. If demand shift > supply shift: P rises, Q rises\n2. If supply shift > demand shift: P falls, Q rises\n3. If shifts are equal: P unchanged, Q rises\n\nDiagram: Draw original D0 and S0 intersecting at E0 (P0, Q0). Shift D right to D1 and S right to S1. Show three possible new equilibrium points:\n- E1a (higher P, higher Q) - if D shift dominates\n- E1b (lower P, higher Q) - if S shift dominates\n- E1c (same P, higher Q) - if shifts equal\nClearly mark Q1 > Q0 in all cases.\n\nReal-World Example - Smartphone Market in Singapore:\n- Demand increase: Rising incomes, 5G network launch, work-from-home needs\n- Supply increase: Manufacturing improvements, more brands entering market\n- Result: Quantity of smartphones sold definitely increased. Price impact depends on which shift was larger. During 2020-2021, we observed Q rising significantly, while prices were relatively stable (suggesting equal shifts) or fell slightly for some models (suggesting supply shift dominated).\n\nConclusion: Quantity increase is certain, price change is indeterminate without knowing relative shift magnitudes.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'hard',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Analyze double shift: Both demand and supply decrease. What is certain and what is indeterminate about the new equilibrium?',
            answer: 'When both demand and supply decrease (D shifts left, S shifts left):\n\nAnalysis:\n- Demand decrease alone: P↓, Q↓\n- Supply decrease alone: P↑, Q↓\n- Combined effect:\n  * Price (P): INDETERMINATE - depends on relative magnitude of shifts\n  * Quantity (Q): CERTAIN to decrease - both shifts decrease Q\n\nThree Scenarios:\n1. If demand shift > supply shift: P falls, Q falls\n2. If supply shift > demand shift: P rises, Q falls\n3. If shifts are equal: P unchanged, Q falls\n\nDiagram: Draw original D0 and S0 intersecting at E0 (P0, Q0). Shift D left to D2 and S left to S2. Show three possible new equilibrium points:\n- E2a (lower P, lower Q) - if D shift dominates\n- E2b (higher P, lower Q) - if S shift dominates\n- E2c (same P, lower Q) - if shifts equal\nClearly mark Q2 < Q0 in all cases.\n\nReal-World Example - Retail Space in Singapore Orchard Road (2020):\n- Demand decrease: COVID-19 restrictions, reduced tourist arrivals, shift to e-commerce\n- Supply decrease: Some landlords withdrew space from market, converted to other uses\n- Result: Quantity of retail space transacted definitely decreased. Price impact depends on which shift was larger. In reality, rental prices fell for most properties (suggesting demand shift dominated), though some prime locations saw stable or rising rents (suggesting supply shift was significant).\n\nConclusion: Quantity decrease is certain, price change is indeterminate without knowing relative shift magnitudes.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'hard',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Analyze double shift: Demand increases while supply decreases. What is certain and what is indeterminate about the new equilibrium?',
            answer: 'When demand increases and supply decreases (D shifts right, S shifts left):\n\nAnalysis:\n- Demand increase alone: P↑, Q↑\n- Supply decrease alone: P↑, Q↓\n- Combined effect:\n  * Price (P): CERTAIN to increase - both shifts increase P\n  * Quantity (Q): INDETERMINATE - depends on relative magnitude of shifts\n\nThree Scenarios:\n1. If demand shift > supply shift: P rises, Q rises\n2. If supply shift > demand shift: P rises, Q falls\n3. If shifts are equal: P rises, Q unchanged\n\nDiagram: Draw original D0 and S0 intersecting at E0 (P0, Q0). Shift D right to D1 and S left to S2. Show three possible new equilibrium points:\n- E1 (higher P, higher Q) - if D shift dominates\n- E2 (higher P, lower Q) - if S shift dominates\n- E3 (higher P, same Q) - if shifts equal\nClearly mark P1 > P0 in all cases, showing upward pressure on price from both shifts.\n\nReal-World Example - Construction Services in Singapore (2021-2022):\n- Demand increase: Post-COVID economic recovery, government infrastructure projects (Thomson-East Coast Line, Changi Airport Terminal 5), strong property market\n- Supply decrease: Labor shortages due to COVID-19 border restrictions, fewer foreign workers, experienced workers retiring\n- Result: Price (construction costs) definitely increased significantly, as both factors pushed prices up. Quantity effect was ambiguous - while demand was strong, supply constraints meant actual construction volume varied by project type. Overall, we observed sharp rises in construction costs (certain) while project completion rates were mixed (indeterminate).\n\nConclusion: Price increase is certain, quantity change is indeterminate without knowing relative shift magnitudes.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'hard',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Analyze double shift: Demand decreases while supply increases. What is certain and what is indeterminate about the new equilibrium?',
            answer: 'When demand decreases and supply increases (D shifts left, S shifts right):\n\nAnalysis:\n- Demand decrease alone: P↓, Q↓\n- Supply increase alone: P↓, Q↑\n- Combined effect:\n  * Price (P): CERTAIN to decrease - both shifts decrease P\n  * Quantity (Q): INDETERMINATE - depends on relative magnitude of shifts\n\nThree Scenarios:\n1. If supply shift > demand shift: P falls, Q rises\n2. If demand shift > supply shift: P falls, Q falls\n3. If shifts are equal: P falls, Q unchanged\n\nDiagram: Draw original D0 and S0 intersecting at E0 (P0, Q0). Shift D left to D2 and S right to S1. Show three possible new equilibrium points:\n- E1 (lower P, higher Q) - if S shift dominates\n- E2 (lower P, lower Q) - if D shift dominates\n- E3 (lower P, same Q) - if shifts equal\nClearly mark P1 < P0 in all cases, showing downward pressure on price from both shifts.\n\nReal-World Example - Crude Oil Market (2020):\n- Demand decrease: Global COVID-19 lockdowns drastically reduced transportation and industrial activity, airlines grounded fleets, reduced business travel\n- Supply increase: OPEC+ production cuts failed initially, leading to excess supply; Saudi Arabia-Russia price war temporarily increased production\n- Result: Price (oil prices) definitely decreased dramatically - WTI crude briefly went negative in April 2020, as both factors pushed prices down sharply. Quantity effect was ambiguous - while demand collapsed, supply initially increased before production cuts took effect. Eventually, actual quantity traded fell as demand destruction was severe.\n\nConclusion: Price decrease is certain (both shifts put downward pressure), quantity change is indeterminate without knowing relative shift magnitudes.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'hard',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Apply shift analysis to the COVID-19 face masks market: Analyze the market changes from pre-pandemic to peak pandemic period.',
            answer: 'COVID-19 Face Masks Market Analysis:\n\nPre-Pandemic Equilibrium (2019):\n- Initial equilibrium: E0 (P0 ≈ $0.10-0.20 per mask, Q0 = low volume)\n- Masks mainly used in healthcare settings and by occasional users\n\nPeak Pandemic Period (Feb-April 2020):\n\nDemand Changes (Rightward shift):\n- Mandatory mask-wearing policies in Singapore (April 2020)\n- Public health awareness and fear of infection\n- Panic buying behavior\n- Government distribution programs creating derived demand\n- Everyone needed masks daily (healthcare, workers, general public)\n- Result: Massive rightward shift in demand (D0 → D1)\n\nSupply Changes (Leftward shift initially):\n- Global supply chain disruptions\n- Export restrictions by mask-producing countries (China, South Korea)\n- Shortage of raw materials (meltblown fabric)\n- Manufacturing capacity constraints\n- Hoarding by intermediaries\n- Result: Significant leftward shift in supply (S0 → S2)\n\nDouble Shift Analysis (D increases, S decreases):\n- Price: CERTAIN to rise (P1 >> P0)\n- Quantity: INDETERMINATE, but demand shift dominated\n\nActual Market Outcome in Singapore:\n- Prices: Surgical masks surged from $0.20 to $2-3 per piece (1000%+ increase)\n- Quantity: Despite high prices, quantity traded increased due to government intervention and mandatory usage\n- Government response: Price controls, direct distribution, ramped up local production\n\nDiagram Description:\nDraw original D0 and S0 intersecting at E0 (low P0, low Q0). Shift D massively right to D1, shift S left to S2. New intersection at E1 shows much higher P1 and moderately higher Q1 (demand shift dominated). Mark areas of shortage at original price.\n\nLong-term adjustment (2021-2023):\n- Supply eventually increased: Local manufacturing (e.g., Razer, ST Engineering), normalized imports\n- Demand moderated: Endemic phase, reduced panic\n- Prices fell back toward $0.30-0.50 range, higher than pre-pandemic but much lower than peak',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'hard',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            question: 'Apply shift analysis to the electric vehicle (EV) market with government subsidies and technological improvements.',
            answer: 'Electric Vehicle Market Analysis with Subsidies and Technology:\n\nInitial Equilibrium (2018-2019):\n- E0: High price (P0 ≈ $150,000+), low quantity (Q0 = few hundred units annually in Singapore)\n- Limited models, range anxiety, insufficient charging infrastructure\n\nMarket Changes (2020-2024):\n\nDemand-Side Factors (Rightward shift D0 → D1):\n\nGovernment Subsidies:\n- EV Early Adoption Incentive (EEAI): Up to $45,000 rebate\n- Additional Registration Fee (ARF) rebates\n- Road tax rebates (45% reduction)\n- Higher carbon tax on petrol vehicles\n- Lower electricity rates for EV charging\n→ Subsidies reduce effective price, shift demand right\n\nOther Demand Factors:\n- Growing environmental consciousness\n- Social status and early adopter appeal\n- Lower running costs over vehicle lifetime\n- Workplace charging facilities\n\nSupply-Side Factors (Rightward shift S0 → S1):\n\nTechnological Improvements:\n- Battery technology: Higher energy density, lower costs (lithium-ion prices fell 89% from 2010-2022)\n- Longer range: From 200km to 400-600km per charge\n- Faster charging: DC fast charging (80% in 30 minutes)\n- Better performance: Instant torque, smoother acceleration\n- More manufacturers entering market (Tesla, BYD, Hyundai, BMW, Mercedes)\n\nProduction Efficiencies:\n- Economies of scale in battery production\n- Cheaper raw materials through innovation\n- Improved manufacturing processes\n- Increased competition among suppliers\n\nDouble Shift Analysis (D increases, S increases):\n- Price: INDETERMINATE (depends on relative magnitude)\n- Quantity: CERTAIN to increase\n\nActual Market Outcome in Singapore:\n- Quantity: Definitely increased from ~650 EVs (2019) to 13,000+ EVs (2023)\n- Price: Mixed effects\n  * List prices fell: Entry-level EVs now around $120,000-140,000\n  * But still premium to comparable petrol cars after subsidies\n  * Supply improvements slightly dominated, causing moderate price decreases\n\nDiagram Description:\nDraw original D0 and S0 at E0 (high P0, low Q0). \nShift D right to D1 (subsidies and preferences).\nShift S right to S1 (technology and competition).\nShow supply shift slightly larger, resulting in E1 with lower P1 and much higher Q1.\nLabel: "Subsidies boost demand, Technology increases supply, Q definitely rises, P falls slightly"\n\nFuture Outlook:\n- As subsidies phase out (scheduled), demand may moderate\n- Continued tech improvements will keep supply increasing\n- Eventually expect prices to converge with petrol vehicles',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Market Equilibrium',
            difficulty: 'hard',
            economicsType: 'Micro',
            chapter: 'Demand, Supply and Market Equilibrium',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    await db.insert(flashcards).values(sampleFlashcards);
    
    console.log('✅ Flashcards equilibrium seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});