import { db } from '@/db';
import { flashcards } from '@/db/schema';

async function main() {
    const sampleFlashcards = [
        // P-TIDE Demand Determinants (10 cards)
        {
            question: 'What does the P in P-TIDE stand for and how does it affect demand?',
            answer: 'P stands for Price of Related Goods. Related goods include substitutes and complements. For substitutes (e.g., Coca-Cola and Pepsi), if the price of one rises, consumers switch to the other, increasing demand for the substitute. This causes a rightward shift of the demand curve. For complements (e.g., cars and petrol), if the price of one rises, demand for both falls, causing a leftward shift of the demand curve for the complement.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain how Taste and Preferences (T in P-TIDE) influences demand with examples.',
            answer: 'Taste and Preferences refer to consumer preferences influenced by trends, advertising, health consciousness, or cultural factors. When tastes favor a good (e.g., increased health awareness leading to demand for organic food), demand increases and the curve shifts right. Conversely, negative perceptions (e.g., concerns about sugar in soft drinks) decrease demand, shifting the curve left. Changes in taste are often driven by marketing campaigns, celebrity endorsements, or social movements.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'How does Income (I in P-TIDE) affect demand for normal and inferior goods?',
            answer: 'Income changes affect demand differently based on good type. For normal goods (luxury and necessity goods), an increase in income increases demand, shifting the curve right. Examples include cars, branded clothing, and holidays. For inferior goods (lower quality alternatives), an increase in income decreases demand as consumers switch to superior substitutes, shifting the curve left. Examples include instant noodles, public transport (when people can afford cars), and second-hand goods.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What is Demographics (D in P-TIDE) and how does it shift the demand curve?',
            answer: 'Demographics refers to population characteristics including size, age structure, income distribution, and geographical distribution. An increase in population size increases demand (rightward shift). Changes in age structure affect demand for specific goods: aging population increases demand for healthcare and retirement homes; younger population increases demand for education and technology. Changes in income distribution affect demand for luxury goods (wealthier population) versus necessities (poorer population).',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain how Expectations (E in P-TIDE) influence current demand with detailed examples.',
            answer: 'Expectations about future prices, income, or availability affect current demand. Price Expectations: If consumers expect prices to rise (e.g., anticipation of GST increase), current demand increases as they stockpile, shifting demand right. If prices are expected to fall (e.g., electronics before new model launch), current demand decreases, shifting left. Income Expectations: Expected promotion or bonus increases current demand for durable goods. Availability Expectations: Expected shortages (e.g., panic buying during COVID-19) increase current demand dramatically.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Distinguish between a movement along the demand curve and a shift of the demand curve.',
            answer: 'A movement along the demand curve (change in quantity demanded) occurs when only the price of the good itself changes, with all other factors constant. Price increase causes upward movement (contraction), price decrease causes downward movement (expansion). A shift of the demand curve (change in demand) occurs when non-price determinants change (P-TIDE factors). Increase in demand shifts curve right, decrease shifts left. Example: Fall in iPhone price causes movement along curve. Rise in income causing more iPhone purchases shifts entire curve right.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Using P-TIDE, explain THREE factors that could increase demand for electric vehicles (EVs).',
            answer: '1) Price of Related Goods (P): Increase in petrol prices makes EVs relatively cheaper to operate, increasing EV demand (substitute effect). 2) Taste and Preferences (T): Growing environmental consciousness and preference for sustainable transport increases demand for EVs. Government campaigns promoting green technology reinforce this. 3) Expectations (E): Expected future petrol price increases or anticipated bans on petrol cars encourage consumers to buy EVs now. Additionally, expectations of improved EV technology and charging infrastructure increase current demand.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'How do complementary goods affect demand? Provide comprehensive examples.',
            answer: 'Complementary goods are consumed together (joint demand). When price of one complement rises, demand for both goods falls. Examples: (1) Cars and Petrol - Higher petrol prices reduce demand for petrol-guzzling cars. (2) Printers and Ink Cartridges - Expensive ink reduces printer demand. (3) Games Consoles and Video Games - Higher console prices reduce demand for games. (4) Coffee and Sugar - Price increase in coffee reduces sugar demand among coffee drinkers. The cross-elasticity of demand (XED) for complements is negative, indicating inverse relationship.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Analyze how an aging population (Demographics in P-TIDE) affects demand across different markets.',
            answer: 'An aging population causes differential demand shifts: INCREASES demand for: Healthcare services and pharmaceuticals, retirement homes and elderly care facilities, medical equipment and mobility aids, insurance products, leisure activities for seniors. DECREASES demand for: Education services (fewer young people), children\'s goods and toys, trendy fashion and technology, sports equipment and gyms. MIXED effects: Housing market shifts from family homes to retirement apartments, food demand shifts from convenience foods to health-focused products. These demographic changes create structural changes in the economy.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What is the difference between luxury goods and necessity goods in terms of income changes?',
            answer: 'Both are normal goods (positive income elasticity) but differ in sensitivity to income changes. LUXURY GOODS: Income Elasticity of Demand (YED) > 1. Demand increases proportionally MORE than income increase. Examples: designer handbags, sports cars, fine dining, overseas holidays. When income rises 10%, demand might rise 20%. These are wants, not needs. NECESSITY GOODS: 0 < YED < 1. Demand increases proportionally LESS than income increase. Examples: rice, basic clothing, public transport, utilities. When income rises 10%, demand might rise only 5%. These are essential goods with limited scope for increased consumption.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // CPPSE Supply Determinants (10 cards)
        {
            question: 'What does the C in CPPSE stand for and how does it affect supply?',
            answer: 'C stands for Cost of Production. This includes costs of raw materials, labor wages, rent, utilities, and technology. When costs of production rise (e.g., higher wages, expensive raw materials, increased rent), producers are less willing and able to supply at each price level, causing leftward shift of supply curve. When costs fall (e.g., cheaper technology, lower material costs, productivity improvements), supply increases, shifting curve right. Cost changes affect profit margins at every price point.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain how Prices of Related Goods (P in CPPSE) affects supply from producer perspective.',
            answer: 'From supply side, related goods are competitive supply (substitutes in production) and joint supply (by-products). COMPETITIVE SUPPLY: Goods produced using same resources (e.g., wheat vs barley on same farmland). If wheat price rises, farmers shift resources to wheat production, reducing barley supply (leftward shift). JOINT SUPPLY: Goods produced together (e.g., beef and leather, petrol and diesel from crude oil). Increase in beef demand increases beef production, automatically increasing leather supply (rightward shift) as they are by-products of same production process.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'How do Producers/Number of Firms (P in CPPSE) influence market supply?',
            answer: 'The number of producers directly affects total market supply. INCREASE in producers: Entry of new firms increases market supply, shifting supply curve right. Occurs when: industry is profitable (high prices), barriers to entry are low, government incentivizes entry. Example: Growth of food delivery platforms increased supply of delivery services. DECREASE in producers: Exit of firms decreases supply, shifting curve left. Occurs when: firms make losses, barriers increase, government restrictions tighten. Example: Closure of unprofitable restaurants reduces food service supply. Each firm\'s exit/entry changes total market supply.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'What are Supply Shocks (S in CPPSE) and how do they affect supply? Provide examples.',
            answer: 'Supply shocks are unexpected events that suddenly affect production capacity. NEGATIVE SHOCKS (decrease supply, leftward shift): Natural disasters - earthquakes destroying factories, floods ruining crops. Pandemics - COVID-19 disrupting production and supply chains. Wars/conflicts - Ukraine war reducing wheat supply. Extreme weather - droughts reducing agricultural output. POSITIVE SHOCKS (increase supply, rightward shift): Technological breakthroughs - new farming techniques increasing yields. Discovery of resources - finding new oil reserves. Favorable weather - perfect growing conditions. Supply shocks are unpredictable and often have immediate, dramatic effects.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain how Expectations (E in CPPSE) affect producers\' supply decisions.',
            answer: 'Producer expectations about future prices, demand, and costs affect current supply. PRICE EXPECTATIONS: If producers expect future price increases, they may withhold current supply (store goods) to sell later at higher prices, decreasing current supply (leftward shift). Example: Farmers storing grain expecting higher future prices. If expecting price decreases, they increase current supply to sell before prices fall (rightward shift). DEMAND EXPECTATIONS: Expected demand increase encourages producers to expand capacity and increase current supply. COST EXPECTATIONS: Expected future cost increases encourage current production expansion before costs rise.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Distinguish between a movement along the supply curve and a shift of the supply curve.',
            answer: 'MOVEMENT ALONG supply curve (change in quantity supplied): Occurs when ONLY the price of the good changes, ceteris paribus. Price increase causes upward movement (expansion of supply). Price decrease causes downward movement (contraction). SHIFT OF supply curve (change in supply): Occurs when non-price determinants change (CPPSE factors). Increase in supply shifts curve RIGHT (more supplied at each price). Decrease shifts LEFT (less supplied at each price). Example: Higher oil prices cause movement along curve. Fall in production costs shifts entire curve right.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'How does technological improvement affect the cost of production and supply curve?',
            answer: 'Technological improvements reduce cost of production through: (1) Increased productivity - same output with fewer inputs. (2) Automation - replacing expensive labor with machinery. (3) Better processes - reduced waste and inefficiency. (4) Improved quality - fewer defects and returns. Lower costs increase profitability at each price level, making producers willing and able to supply more. This shifts supply curve RIGHT. Examples: Agricultural technology increasing crop yields per hectare. 3D printing reducing manufacturing costs. AI improving efficiency in services. Renewable energy technology reducing energy costs.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Using CPPSE, explain THREE factors that could decrease supply of semiconductor chips.',
            answer: '1) Cost of Production (C): Rising costs of rare earth materials, expensive manufacturing equipment, and higher electricity prices increase production costs, reducing supply (leftward shift). 2) Supply Shocks (S): Natural disasters (earthquakes in Taiwan/Japan) destroying fabrication plants, or water shortages affecting production (chip manufacturing needs pure water). 3) Producers (P): Exit of firms due to intense competition and capital requirements. If smaller manufacturers cannot compete with industry giants, their exit reduces total market supply. Additionally, trade restrictions and export controls can effectively reduce supply in certain markets.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the concept of joint supply with comprehensive examples and implications.',
            answer: 'Joint supply occurs when production of one good automatically produces another good as by-product. CHARACTERISTICS: (1) Fixed proportions - cannot produce one without the other. (2) Shared production process. (3) Interdependent supply. EXAMPLES: Beef and Leather - slaughtering cattle produces both. Increase in beef demand increases beef production, automatically increasing leather supply. Crude Oil refining - produces petrol, diesel, kerosene simultaneously. Sheep farming - produces lamb meat and wool. Lumber production - produces timber and sawdust. IMPLICATIONS: Supply of joint products moves together. Price of one product affects profitability and production levels of both.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'How do government subsidies and taxes affect the cost of production and supply?',
            answer: 'SUBSIDIES (payments to producers): Reduce effective cost of production, acting as negative cost. Increase supply by shifting curve RIGHT. Producers willing to supply more at each price as costs are lower. Examples: Agricultural subsidies, renewable energy subsidies, R&D grants. TAXES on producers (e.g., carbon tax, corporate tax): Increase cost of production. Decrease supply by shifting curve LEFT. Producers less willing to supply at each price as costs are higher. Examples: Emission taxes on polluting industries, excise duties on manufacturers. Both represent changes in Cost of Production (C in CPPSE), affecting supply curve position.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Price Elasticity of Demand (10 cards)
        {
            question: 'Define Price Elasticity of Demand (PED) and state its formula with interpretation.',
            answer: 'PED measures responsiveness of quantity demanded to price changes. FORMULA: PED = (% change in Qd) / (% change in P). Always NEGATIVE (inverse relationship - law of demand). INTERPRETATION: PED = -2 means 1% price increase causes 2% quantity demanded decrease. Use ABSOLUTE VALUES: |PED| > 1 = Price Elastic (responsive). |PED| < 1 = Price Inelastic (unresponsive). |PED| = 1 = Unit Elastic. |PED| = 0 = Perfectly Inelastic (vertical demand curve). |PED| = ∞ = Perfectly Elastic (horizontal demand curve).',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the SNIT determinants of Price Elasticity of Demand in detail.',
            answer: 'S - SUBSTITUTES: More close substitutes = more elastic. Consumers can switch easily. Example: Coca-Cola has many substitutes (Pepsi), so elastic. Life-saving drugs have no substitutes, so inelastic. N - NECESSITY: Necessities are inelastic (must buy regardless of price). Luxuries are elastic (can postpone/forego). I - INCOME PROPORTION: Goods taking large income proportion are elastic (cars). Small proportion goods are inelastic (salt, matches). T - TIME: Demand more elastic in long run. Consumers need time to find alternatives, adjust habits, or find substitutes. Short run demand more inelastic due to limited options.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the relationship between Price Elasticity of Demand and Total Revenue for price increases.',
            answer: 'PRICE ELASTIC DEMAND (|PED| > 1): Price increase causes proportionally larger quantity decrease. Total Revenue (P × Q) FALLS. %ΔQ > %ΔP. Example: Luxury goods - 10% price increase causes 20% demand fall, revenue decreases. PRICE INELASTIC DEMAND (|PED| < 1): Price increase causes proportionally smaller quantity decrease. Total Revenue RISES. %ΔQ < %ΔP. Example: Petrol - 10% price increase causes 5% demand fall, revenue increases. UNIT ELASTIC (|PED| = 1): Price increase causes equal proportional quantity decrease. Total Revenue UNCHANGED. This relationship is crucial for firms\' pricing strategies.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the relationship between Price Elasticity of Demand and Total Revenue for price decreases.',
            answer: 'PRICE ELASTIC DEMAND (|PED| > 1): Price decrease causes proportionally larger quantity increase. Total Revenue RISES. Example: Electronics - price cut increases sales significantly, boosting total revenue. Firms should lower prices for elastic demand goods. PRICE INELASTIC DEMAND (|PED| < 1): Price decrease causes proportionally smaller quantity increase. Total Revenue FALLS. Example: Salt - price cut barely increases consumption, reducing revenue. Firms should maintain/raise prices for inelastic goods. UNIT ELASTIC (|PED| = 1): Total Revenue unchanged. These relationships guide pricing decisions and revenue maximization strategies.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Why do necessities tend to have price inelastic demand? Provide detailed examples.',
            answer: 'Necessities are ESSENTIAL goods required for daily living, regardless of price. CHARACTERISTICS: (1) No close substitutes - consumers must buy them. (2) Cannot postpone consumption - needed immediately. (3) Usually take small income proportion. EXAMPLES: Rice/staple foods - must eat despite price increases. Medicine - life-dependent, no alternatives. Electricity/water - essential utilities with limited alternatives. Petrol (short run) - needed for work/transport. Public transport - essential for commuting. IMPLICATION: Demand changes little when price changes (|PED| < 1). Suppliers can raise prices without losing many customers, but government intervention often needed to protect consumers.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Why do luxury goods tend to have price elastic demand? Provide detailed examples.',
            answer: 'Luxuries are NON-ESSENTIAL goods that enhance lifestyle but are not necessary. CHARACTERISTICS: (1) Many substitutes available or can forego entirely. (2) Consumption can be postponed. (3) Usually take large income proportion. (4) Want, not need. EXAMPLES: Designer handbags - many alternatives, can delay purchase. Sports cars - can use regular cars instead. Fine dining - can cook at home or eat cheaper food. Overseas holidays - can postpone or choose domestic travel. Latest smartphones - can keep old phone longer. IMPLICATION: Demand very sensitive to price (|PED| > 1). Price increases cause large demand falls as consumers switch to alternatives or postpone purchases.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain why demand becomes more elastic over time. Use comprehensive examples.',
            answer: 'TIME allows consumers to adjust behavior and find alternatives. SHORT RUN: Demand relatively inelastic because: (1) Consumers unaware of alternatives. (2) Contracts/commitments limit changes. (3) Habits hard to break immediately. (4) Takes time to find substitutes. LONG RUN: Demand becomes elastic because: (1) Consumers research and find substitutes. (2) Contracts expire, allowing switches. (3) New habits form. (4) Technology provides alternatives. EXAMPLE: Petrol - Short run: must buy for commuting (inelastic). Long run: buy fuel-efficient car, use public transport, relocate closer to work (elastic). Cigarettes - Short run: addiction makes demand inelastic. Long run: can quit or find alternatives (elastic).',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'How does availability of substitutes affect PED? Explain with specific examples.',
            answer: 'MORE substitutes = MORE elastic demand. Consumers easily switch when price rises. MANY SUBSTITUTES (Elastic): Coca-Cola vs Pepsi, Sprite, Fanta - many alternatives. Restaurant meals - can choose different restaurants. Branded clothes - many fashion brands available. Margarine vs butter - interchangeable. ONE substitute price increase causes large quantity demanded fall as consumers switch. FEW/NO SUBSTITUTES (Inelastic): Insulin for diabetics - no substitute, life-dependent. Table salt - no good alternative. Electricity - limited alternatives for home use. Petrol (short run) - electric vehicles still limited. Must continue buying despite price increases. PED closely tied to substitutability.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Calculate PED and interpret: Price falls from $50 to $45, quantity demanded rises from 1000 to 1200 units.',
            answer: 'CALCULATION: %ΔP = [(45-50)/50] × 100 = -10%. %ΔQd = [(1200-1000)/1000] × 100 = +20%. PED = 20% / -10% = -2. INTERPRETATION: |PED| = 2 > 1, therefore demand is PRICE ELASTIC. A 1% price decrease causes 2% quantity demanded increase. Demand is responsive to price changes. TOTAL REVENUE IMPACT: Original TR = $50 × 1000 = $50,000. New TR = $45 × 1200 = $54,000. TR increased by $4,000. This confirms elastic demand - price decrease increases total revenue. BUSINESS IMPLICATION: Firm should consider price reductions to boost revenue.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain perfectly inelastic and perfectly elastic demand with real-world examples and graphical representations.',
            answer: 'PERFECTLY INELASTIC (PED = 0): Quantity demanded unchanged regardless of price. VERTICAL demand curve. Examples: Life-saving emergency medicine, insulin for diabetics (short run), essential surgery. Consumers pay any price as no alternative exists. Zero responsiveness to price. PERFECTLY ELASTIC (PED = ∞): Any price increase causes quantity demanded to fall to zero. HORIZONTAL demand curve. Theoretical concept in perfect competition where many identical substitutes exist. If one seller raises price, all consumers switch to competitors. Examples approximating this: Individual farmer\'s wheat (commodity markets), currencies in forex markets. Extreme price sensitivity.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Price Elasticity of Supply (5 cards)
        {
            question: 'Define Price Elasticity of Supply (PES) and state its formula with interpretation.',
            answer: 'PES measures responsiveness of quantity supplied to price changes. FORMULA: PES = (% change in Qs) / (% change in P). Always POSITIVE (direct relationship). INTERPRETATION: PES = 2 means 1% price increase causes 2% quantity supplied increase. VALUES: PES > 1 = Price Elastic Supply (responsive). PES < 1 = Price Inelastic Supply (unresponsive). PES = 1 = Unit Elastic. PES = 0 = Perfectly Inelastic (vertical supply curve, fixed quantity). PES = ∞ = Perfectly Elastic (horizontal supply curve). Higher PES means producers can quickly adjust output in response to price changes.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the TIME determinant of Price Elasticity of Supply in detail with examples.',
            answer: 'TIME is crucial for supply adjustments. THREE TIME PERIODS: IMMEDIATE/MARKET RUN (hours/days): Supply perfectly/highly inelastic. Cannot increase output - only sell existing stock. Example: Fresh fish catch, concert tickets, hotel rooms tonight. PES ≈ 0. SHORT RUN (weeks/months): Supply relatively inelastic. Can increase output using existing capacity (overtime, extra shifts) but cannot expand capacity. Example: Factories running 24/7. PES < 1. LONG RUN (years): Supply elastic. Can build new factories, hire/train workers, buy machinery, develop new technology. Example: Automobile production expanding. PES > 1. Longer time = more elastic supply as firms can fully adjust.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain how SPARE CAPACITY affects Price Elasticity of Supply with examples.',
            answer: 'SPARE CAPACITY = unused production capability. WITH SPARE CAPACITY: Supply MORE ELASTIC. Can quickly increase output using idle resources (workers, machines, space). Little additional cost needed. Examples: Factory operating at 60% capacity can easily increase to 80%. Airlines with empty seats can add passengers at low cost. Restaurants with empty tables during off-peak. Retailers with warehouse stock. WITHOUT SPARE CAPACITY: Supply INELASTIC. Operating at full capacity - cannot increase output without new investment. Examples: Fully-booked hotel during peak season. Semiconductor fabs running 24/7. Agricultural land all in use. Must build new capacity (time-consuming and expensive) before increasing supply.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'How does NATURE OF PRODUCTION affect Price Elasticity of Supply? Compare manufacturing vs agriculture.',
            answer: 'MANUFACTURING (Elastic Supply): Can adjust output relatively quickly. Hire workers, buy materials, run extra shifts. Standardized processes allow scaling. Examples: Electronics, clothing, furniture. Can respond to price increases by increasing production in weeks/months. AGRICULTURE (Inelastic Supply): Long production cycles. Cannot speed up growth (wheat takes months to grow). Weather-dependent. Seasonal constraints. Examples: Rice, fruits, livestock. Even with high prices, supply fixed until next harvest. Cannot quickly respond. SERVICES: Varies - haircuts relatively elastic (hire more barbers), specialized medical services inelastic (need trained doctors, takes years). Production nature determines supply responsiveness.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain STOCK LEVELS/INVENTORY and FACTOR MOBILITY as determinants of PES with examples.',
            answer: 'STOCK LEVELS: HIGH stocks = ELASTIC supply. Can quickly supply from inventory when price rises. Example: Retailers with warehouse stock, oil reserves. LOW stocks = INELASTIC supply. Must produce new goods, taking time. Example: Made-to-order furniture, custom products. FACTOR MOBILITY: HIGH mobility = ELASTIC supply. Resources easily switched between uses. Workers easily retrained, machinery versatile, materials readily available. Example: General manufacturing, retail services. LOW mobility = INELASTIC supply. Specialized resources cannot be repurposed. Example: Aircraft manufacturing needs specialized engineers and equipment (cannot quickly repurpose from other industries). Medical professionals need years of training. Greater mobility allows faster supply responses to price changes.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Income Elasticity of Demand (5 cards)
        {
            question: 'Define Income Elasticity of Demand (YED) and explain its formula with interpretation for all types of goods.',
            answer: 'YED measures responsiveness of demand to income changes. FORMULA: YED = (% change in Qd) / (% change in Y). NORMAL GOODS (YED > 0, positive): Demand increases with income. LUXURY goods: YED > 1 (income elastic). Demand rises proportionally MORE than income. Examples: sports cars, designer goods, holidays. NECESSITY goods: 0 < YED < 1 (income inelastic). Demand rises proportionally LESS than income. Examples: rice, basic clothing, utilities. INFERIOR GOODS (YED < 0, negative): Demand FALLS as income rises. Consumers switch to superior alternatives. Examples: instant noodles, second-hand goods, public transport (when can afford car).',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the characteristics and examples of LUXURY GOODS (income elastic normal goods) in detail.',
            answer: 'LUXURY goods have YED > 1 (income elastic demand). CHARACTERISTICS: (1) Non-essential, enhance lifestyle. (2) High income proportion of spending. (3) Demand very responsive to income changes. (4) Status symbols. (5) Can postpone/forego purchases. EXAMPLES: Designer fashion (Gucci, Prada), luxury cars (Ferrari, Rolls-Royce), fine dining at Michelin restaurants, first-class air travel, jewelry and watches, private education, overseas holidays, smart home technology. IMPLICATION: In economic boom (rising incomes), luxury goods see large demand increases. In recession (falling incomes), luxury demand falls sharply. Luxury industries are cyclical and income-sensitive.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain the characteristics and examples of NECESSITY GOODS (income inelastic normal goods) comprehensively.',
            answer: 'NECESSITY goods have 0 < YED < 1 (income inelastic positive demand). CHARACTERISTICS: (1) Essential for daily living. (2) Limited scope for increased consumption regardless of income. (3) Small income proportion. (4) Demand relatively stable across income levels. (5) Basic versions consumed by all income groups. EXAMPLES: Staple foods (rice, bread, vegetables), basic utilities (water, electricity - basic usage), basic clothing, public healthcare, basic telecommunications, toothpaste, soap. IMPLICATION: Even as income rises, consumption increases only slightly (already consuming enough). These goods have stable, recession-resistant demand. Essential for low-income households.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain INFERIOR GOODS with detailed examples and why demand falls as income rises.',
            answer: 'INFERIOR goods have NEGATIVE YED (YED < 0). Demand DECREASES as income INCREASES. WHY: As consumers become wealthier, they switch from inferior goods to superior alternatives (normal goods). Inferior goods are lower-quality, less desirable options consumed due to budget constraints. EXAMPLES: Instant noodles → restaurant meals (when richer). Second-hand goods → new products. Public transport → private cars. Cheap processed foods → fresh, organic foods. Budget airlines → full-service airlines. Shared accommodation → private housing. Generic brands → premium brands. NOT necessarily poor quality, just less preferred when affordable alternatives exist. Different goods can be inferior for different income groups.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Calculate YED and classify the good: Income rises from $3000 to $3600, quantity demanded increases from 100 to 130 units.',
            answer: 'CALCULATION: %ΔY = [(3600-3000)/3000] × 100 = +20%. %ΔQd = [(130-100)/100] × 100 = +30%. YED = 30% / 20% = +1.5. CLASSIFICATION: YED = +1.5 (positive and > 1). This is a LUXURY GOOD (income elastic normal good). INTERPRETATION: A 1% income increase causes 1.5% demand increase. Demand rises proportionally MORE than income. Good is income-sensitive and non-essential. EXAMPLES of such goods: Designer clothing, fine dining, overseas travel, sports cars. BUSINESS IMPLICATION: Sales will grow faster than economy during booms but fall sharply during recessions. Target affluent consumers and adjust production with economic cycles.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Cross Elasticity of Demand (5 cards)
        {
            question: 'Define Cross Elasticity of Demand (XED) and explain its formula with interpretation for all relationship types.',
            answer: 'XED measures responsiveness of demand for Good A to price changes of Good B. FORMULA: XED = (% change in Qd of A) / (% change in P of B). SUBSTITUTES (XED > 0, POSITIVE): Goods consumed in place of each other. Price of B rises → Demand for A increases. Examples: Coca-Cola and Pepsi (XED ≈ +0.8), butter and margarine. Closer substitutes = higher positive XED. COMPLEMENTS (XED < 0, NEGATIVE): Goods consumed together. Price of B rises → Demand for A falls. Examples: cars and petrol (XED ≈ -0.5), printers and ink. Stronger complementarity = more negative XED. UNRELATED goods (XED ≈ 0): No relationship. Examples: bread and smartphones.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain SUBSTITUTE goods and XED with comprehensive examples showing different degrees of substitutability.',
            answer: 'SUBSTITUTES have POSITIVE XED. Can replace each other in consumption. CLOSE SUBSTITUTES (High positive XED): Very similar, easily interchangeable. Coca-Cola vs Pepsi (XED ≈ +0.8). Butter vs margarine. Different petrol stations. iPhone vs Samsung. Price increase of one causes large demand increase for other. WEAK SUBSTITUTES (Low positive XED): Less similar, limited interchangeability. Tea vs coffee (XED ≈ +0.2). Train vs airplane for long distances. Cinema vs streaming services. Price increase of one causes small demand increase for other. DEGREE OF SUBSTITUTABILITY depends on: similarity, ease of switching, consumer preferences, price differential.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain COMPLEMENTARY goods and XED with detailed examples showing different degrees of complementarity.',
            answer: 'COMPLEMENTS have NEGATIVE XED. Consumed together (joint demand). STRONG COMPLEMENTS (Highly negative XED): Used together in fixed proportions. Cars and petrol (XED ≈ -0.5). Printers and ink cartridges. Mobile phones and data plans. Games consoles and video games. Coffee machines and coffee pods. Price increase of one causes large demand decrease for other. WEAK COMPLEMENTS (Low negative XED): Used together but less dependent. Bread and butter (XED ≈ -0.1). Cinema tickets and popcorn. Hotels and tourism activities. Price increase of one causes small demand decrease for other. Complementarity strength depends on necessity of joint use.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'How do firms use XED information for pricing and product strategies? Provide detailed applications.',
            answer: 'SUBSTITUTE PRODUCTS (Positive XED): COMPETITIVE PRICING: Must consider competitor prices. Price too high loses customers to substitutes. DIFFERENTIATION: Create unique features to reduce substitutability, lowering XED. Example: Apple ecosystem makes switching costly. PROMOTION: When competitor raises prices, increase marketing to attract their customers. COMPLEMENTARY PRODUCTS (Negative XED): BUNDLING: Sell complements together at discount. Example: Razors cheap, blades expensive. CROSS-SELLING: Promote related products. Example: Recommend printer when selling computer. PRICING STRATEGY: Can raise price of one if other is essential. Example: Games console cheap to sell games. MARKET EXPANSION: Growth in one product boosts demand for complement.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Calculate XED and determine relationship: Good A demand increases from 100 to 120 units when Good B price rises from $50 to $60.',
            answer: 'CALCULATION: %ΔP(B) = [(60-50)/50] × 100 = +20%. %ΔQd(A) = [(120-100)/100] × 100 = +20%. XED = 20% / 20% = +1. INTERPRETATION: XED = +1 (positive). Goods A and B are SUBSTITUTES. DEGREE: XED = +1 indicates moderate substitutability. When Good B price rises 1%, demand for Good A increases 1%. EXAMPLE: Could be Coca-Cola (A) and Pepsi (B), or butter (A) and margarine (B). BUSINESS IMPLICATION: Firms competing with Good B should monitor B\'s pricing. When B raises prices, Good A can capture market share. Could also slightly raise A\'s price to maximize revenue. Both goods compete for same consumers.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Government Intervention (5 cards)
        {
            question: 'Compare SPECIFIC TAX and AD VALOREM TAX with detailed effects on supply, price, and quantity.',
            answer: 'SPECIFIC TAX: Fixed amount per unit (e.g., $2 per pack). Effect: Parallel leftward supply shift. Tax burden same regardless of price. Example: cigarette duty of $5 per pack. Post-tax price: P + tax. AD VALOREM TAX: Percentage of price (e.g., 7% GST). Effect: Supply curve rotates left (steeper). Tax burden increases with price. Higher-priced goods bear more tax. Example: 7% GST, luxury car tax. Post-tax price: P(1 + tax rate). INCIDENCE: Both types split between consumers and producers depending on PED and PES. More inelastic side bears larger burden. Both reduce equilibrium quantity. Both cause deadweight loss (welfare loss).',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain SUBSIDY effects on supply curve, price, quantity, and welfare with comprehensive analysis.',
            answer: 'SUBSIDY: Government payment to producers per unit (opposite of tax). SUPPLY CURVE: Shifts RIGHT (parallel shift). Producers receive price + subsidy, willing to supply more at each price. EFFECTS: Equilibrium price DECREASES (consumers benefit). Equilibrium quantity INCREASES. Producer revenue INCREASES (price received = market price + subsidy). WELFARE: Consumer Surplus increases (lower price, more consumption). Producer Surplus increases (higher effective price received). Government spending = subsidy × quantity (taxpayer cost). DEADWEIGHT LOSS: Society overproduces beyond allocatively efficient level. Examples: Agricultural subsidies, renewable energy subsidies, public transport subsidies. Justifications: support essential industries, correct positive externalities, income redistribution.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain PRICE CEILING with effects, examples, and welfare analysis including shortages and black markets.',
            answer: 'PRICE CEILING: Maximum legal price, set BELOW equilibrium. EFFECTS: At ceiling price Pc < Pe: Quantity demanded > Quantity supplied → SHORTAGE. Qd - Qs = shortage amount. CONSEQUENCES: Rationing needed (queuing, balloting, favoritism). Black markets emerge (illegal selling above ceiling). Quality deterioration (producers cut costs). WELFARE: Consumer Surplus: Gainers (who get goods at lower price) and Losers (cannot buy due to shortage). Producer Surplus DECREASES (lower price, less sold). Deadweight Loss from underproduction. EXAMPLES: Rent control (affordable housing shortage). Wartime price controls. Interest rate caps. JUSTIFICATION: Protect low-income consumers, ensure affordability. PROBLEMS: Shortages, inefficiency, black markets, reduced investment.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Explain PRICE FLOOR with effects, examples, and welfare analysis including surpluses and government intervention.',
            answer: 'PRICE FLOOR: Minimum legal price, set ABOVE equilibrium. EFFECTS: At floor price Pf > Pe: Quantity supplied > Quantity demanded → SURPLUS. Qs - Qd = surplus amount. Producers want to sell more than consumers want to buy. CONSEQUENCES: Government must buy surplus (taxpayer cost) or surplus wasted. Production inefficiency. Resources misallocated. WELFARE: Producer Surplus: Gainers (sell at higher price) and Losers (cannot sell surplus). Consumer Surplus DECREASES (higher price, less consumed). Deadweight Loss from underproduction. EXAMPLES: Minimum wage (unemployment if above equilibrium wage). Agricultural price supports. JUSTIFICATION: Protect producer income, ensure fair wages. PROBLEMS: Surpluses, unemployment (if labor market), government expenditure, inefficiency.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            question: 'Analyze tax incidence (burden distribution) between consumers and producers based on elasticity with detailed examples.',
            answer: 'TAX INCIDENCE: How tax burden splits between consumers (price increase) and producers (revenue decrease). DEPENDS ON ELASTICITY: INELASTIC DEMAND, ELASTIC SUPPLY: Consumers bear MOST burden. Cannot reduce consumption much, producers can reduce supply. Example: Cigarette tax - smokers addicted (inelastic), can\'t quit easily. ELASTIC DEMAND, INELASTIC SUPPLY: Producers bear MOST burden. Consumers can switch/reduce consumption easily, producers cannot reduce supply. Example: Agricultural products - consumers switch crops easily, farmers cannot. EQUAL ELASTICITY: Equal burden sharing. PERFECTLY INELASTIC DEMAND: Consumers bear ENTIRE tax (price rises by full tax). GENERAL RULE: More inelastic side bears larger tax burden as they have less ability to adjust behavior.',
            level: 'JC',
            category: 'H2 Economics',
            topic: 'Microeconomics',
            economicsType: 'Micro',
            chapter: 'Demand and Supply',
            difficulty: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(flashcards).values(sampleFlashcards);
    
    console.log('✅ Flashcards seeder completed successfully - 50 JC H2 Economics Demand and Supply cards created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});